/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.networkadminrole;

import business.EcoSystem;
import business.HelperMethods;
import business.enterprise.Enterprise;
import business.network.Network;
import business.person.Person;
import business.role.EnterpriseAdminRole;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JAHNVI
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private Network network;
    /**
     * Creates new form ManageEnterpriseAdminJPanel
     */
    public ManageEnterpriseAdminJPanel() {
        initComponents();
    }
    
    public ManageEnterpriseAdminJPanel(JPanel userProcessContainer, EcoSystem system, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.network = network;
        networkNameLbl.setText(network.getOrganizationName());
        errorMsgLbl.setVisible(false);
        populateEnterpriseAdminTable();
        bindEnterpriseCombo();
    }

    public void populateEnterpriseAdminTable() {
        DefaultTableModel dtm = (DefaultTableModel) enterpriseAdminTable.getModel();
        dtm.setRowCount(0);
        
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            
            if (enterprise.getUserAccountDirectory().getUserAccountDirectory().size() > 0) {
                Object row[] = new Object[5];
                row[0] = enterprise.getOrganizationId();
                row[1] = enterprise;
                row[2] = enterprise.getEnterpriseType().getValue();
                row[3] = enterprise.getUserAccountDirectory().getUserAccountDirectory().get(0).getPerson().getFirstName();
                row[4] = enterprise.getUserAccountDirectory().getUserAccountDirectory().get(0);
            
                dtm.addRow(row);
            }
        }
    }
    
    public void bindEnterpriseCombo() {
        enterpriseCombo.removeAllItems();
        
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise.getUserAccountDirectory().getUserAccountDirectory().isEmpty()) {
                enterpriseCombo.addItem(enterprise);
            }
        }
        
        if (enterpriseCombo.getItemCount() == 0) {
            addEnterpriseAdminBtn.setEnabled(false);
            errorMsgLbl.setText("All Enterprises are assigned an Enterprise Admin!");
            errorMsgLbl.setVisible(true);
        }
        else {
            errorMsgLbl.setVisible(false);
            addEnterpriseAdminBtn.setEnabled(true);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        titleLbl = new javax.swing.JLabel();
        networkNameLbl = new javax.swing.JLabel();
        networkLbl = new javax.swing.JLabel();
        enterpriseAdminLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseAdminTable = new javax.swing.JTable();
        deleteAdminBtn = new javax.swing.JButton();
        viewDetailsBtn = new javax.swing.JButton();
        selectEnterpriseLbl = new javax.swing.JLabel();
        enterpriseCombo = new javax.swing.JComboBox();
        maleRadioBtn = new javax.swing.JRadioButton();
        femaleRadioBtn = new javax.swing.JRadioButton();
        firstNameLbl = new javax.swing.JLabel();
        firstNameTxt = new javax.swing.JTextField();
        lastNameLbl = new javax.swing.JLabel();
        usernameLbl = new javax.swing.JLabel();
        lastNameTxt = new javax.swing.JTextField();
        usernameTxt = new javax.swing.JTextField();
        contactNoLbl = new javax.swing.JLabel();
        pwdLbl = new javax.swing.JLabel();
        contactNoTxt = new javax.swing.JTextField();
        pwdTxt = new javax.swing.JPasswordField();
        genderLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        addEnterpriseAdminBtn = new javax.swing.JButton();
        errorMsgLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(740, 670));

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 102, 102));
        titleLbl.setText("Network Admin - Manage Enterprise Admin");

        networkNameLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        networkNameLbl.setForeground(new java.awt.Color(0, 102, 102));
        networkNameLbl.setText("<Network>");

        networkLbl.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        networkLbl.setForeground(new java.awt.Color(0, 102, 102));
        networkLbl.setText("Network:");

        enterpriseAdminLbl.setForeground(new java.awt.Color(0, 102, 102));
        enterpriseAdminLbl.setText("Enterprise Admin List:");

        jScrollPane1.setForeground(new java.awt.Color(0, 102, 102));

        enterpriseAdminTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Enterprise Id", "Enterprise Name", "Enterprise Type", "Admin Name", "User Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(enterpriseAdminTable);
        if (enterpriseAdminTable.getColumnModel().getColumnCount() > 0) {
            enterpriseAdminTable.getColumnModel().getColumn(0).setResizable(false);
            enterpriseAdminTable.getColumnModel().getColumn(1).setResizable(false);
            enterpriseAdminTable.getColumnModel().getColumn(2).setResizable(false);
            enterpriseAdminTable.getColumnModel().getColumn(3).setResizable(false);
            enterpriseAdminTable.getColumnModel().getColumn(4).setResizable(false);
        }

        deleteAdminBtn.setBackground(new java.awt.Color(153, 153, 153));
        deleteAdminBtn.setForeground(new java.awt.Color(0, 102, 102));
        deleteAdminBtn.setText("Delete Enterprise Admin");
        deleteAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAdminBtnActionPerformed(evt);
            }
        });

        viewDetailsBtn.setBackground(new java.awt.Color(153, 153, 153));
        viewDetailsBtn.setForeground(new java.awt.Color(0, 102, 102));
        viewDetailsBtn.setText("View Details");
        viewDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsBtnActionPerformed(evt);
            }
        });

        selectEnterpriseLbl.setForeground(new java.awt.Color(0, 102, 102));
        selectEnterpriseLbl.setText("Select Enterprise:");

        enterpriseCombo.setForeground(new java.awt.Color(0, 102, 102));
        enterpriseCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroup1.add(maleRadioBtn);
        maleRadioBtn.setForeground(new java.awt.Color(0, 102, 102));
        maleRadioBtn.setText("Male");

        buttonGroup1.add(femaleRadioBtn);
        femaleRadioBtn.setForeground(new java.awt.Color(0, 102, 102));
        femaleRadioBtn.setText("Female");

        firstNameLbl.setForeground(new java.awt.Color(0, 102, 102));
        firstNameLbl.setText("First Name:");

        firstNameTxt.setForeground(new java.awt.Color(0, 102, 102));

        lastNameLbl.setForeground(new java.awt.Color(0, 102, 102));
        lastNameLbl.setText("Last Name:");

        usernameLbl.setForeground(new java.awt.Color(0, 102, 102));
        usernameLbl.setText("User Name:");

        lastNameTxt.setForeground(new java.awt.Color(0, 102, 102));

        usernameTxt.setForeground(new java.awt.Color(0, 102, 102));

        contactNoLbl.setForeground(new java.awt.Color(0, 102, 102));
        contactNoLbl.setText("Contact No.:");

        pwdLbl.setForeground(new java.awt.Color(0, 102, 102));
        pwdLbl.setText("Password:");

        contactNoTxt.setForeground(new java.awt.Color(0, 102, 102));

        pwdTxt.setForeground(new java.awt.Color(0, 102, 102));

        genderLbl.setForeground(new java.awt.Color(0, 102, 102));
        genderLbl.setText("Gender:");

        backBtn.setBackground(new java.awt.Color(153, 153, 153));
        backBtn.setForeground(new java.awt.Color(0, 102, 102));
        backBtn.setText("<<  Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        addEnterpriseAdminBtn.setBackground(new java.awt.Color(153, 153, 153));
        addEnterpriseAdminBtn.setForeground(new java.awt.Color(0, 102, 102));
        addEnterpriseAdminBtn.setText("Add Enterprise Admin");
        addEnterpriseAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEnterpriseAdminBtnActionPerformed(evt);
            }
        });

        errorMsgLbl.setForeground(new java.awt.Color(255, 102, 102));
        errorMsgLbl.setText("<Error Message>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(titleLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(viewDetailsBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteAdminBtn))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(enterpriseAdminLbl)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(networkLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(networkNameLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(genderLbl)
                            .addComponent(contactNoLbl)
                            .addComponent(lastNameLbl)
                            .addComponent(firstNameLbl)
                            .addComponent(selectEnterpriseLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(maleRadioBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(contactNoTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastNameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstNameTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(usernameLbl)
                                    .addComponent(pwdLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usernameTxt)
                                    .addComponent(pwdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(enterpriseCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(femaleRadioBtn)
                                .addGap(153, 153, 153)
                                .addComponent(addEnterpriseAdminBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(errorMsgLbl)))
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(networkLbl)
                    .addComponent(networkNameLbl))
                .addGap(38, 38, 38)
                .addComponent(enterpriseAdminLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteAdminBtn)
                    .addComponent(viewDetailsBtn))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectEnterpriseLbl)
                    .addComponent(enterpriseCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameLbl)
                            .addComponent(firstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameLbl)
                            .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameLbl)
                            .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pwdLbl)
                        .addComponent(pwdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNoLbl)
                    .addComponent(contactNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLbl)
                    .addComponent(maleRadioBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addEnterpriseAdminBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(femaleRadioBtn)
                        .addGap(17, 17, 17)))
                .addGap(15, 15, 15)
                .addComponent(errorMsgLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addEnterpriseAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEnterpriseAdminBtnActionPerformed
        // TODO add your handling code here:
        if(validateInput()) {
            Enterprise enterprise = (Enterprise) enterpriseCombo.getSelectedItem();
            
            if (enterprise != null) {
                Person person = new Person(); 
                person.setFirstName(firstNameTxt.getText().trim());
                person.setLastName(lastNameTxt.getText().trim());
                person.setContactNo(contactNoTxt.getText().trim());
                
                enterprise.getPersonDirectory().addPerson(person);
                
                if(maleRadioBtn.isSelected()) {
                    person.setGender("Male");
                }
                else {
                    person.setGender("Female");
                }
                
                UserAccount ua = enterprise.getUserAccountDirectory().createUserAccount(usernameTxt.getText().trim(), String.valueOf(pwdTxt.getPassword()), person, new EnterpriseAdminRole());
                
                if (ua != null) {
                    JOptionPane.showMessageDialog(null, "Enterprise Admin Account created successfully!", "information", JOptionPane.INFORMATION_MESSAGE);
                    refresh();
                }
            }
            else {
                JOptionPane.showMessageDialog(null, "Please select an enterprise to add Admin!", "Warning", JOptionPane.WARNING_MESSAGE);
                enterpriseCombo.requestFocus();
            }
        }
    }//GEN-LAST:event_addEnterpriseAdminBtnActionPerformed

    private void deleteAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAdminBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = enterpriseAdminTable.getSelectedRow();
        
        if (selectedRow >= 0) {
            int confirmButton = JOptionPane.YES_NO_OPTION;
            
            int confirmDelete = JOptionPane.showConfirmDialog(null, "Would you like to delete selected enterprise admin?", "Warning", confirmButton);
            
            if (confirmDelete == JOptionPane.YES_OPTION) {
                UserAccount ua = (UserAccount) enterpriseAdminTable.getValueAt(selectedRow, 4);
                Enterprise enterprise = (Enterprise) enterpriseAdminTable.getValueAt(selectedRow, 1);
                
                enterprise.getUserAccountDirectory().removeUserAccount(ua);
                enterprise.getPersonDirectory().removePerson(ua.getPerson());
                
                refresh();
            }  
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a row to delete Network Admin!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteAdminBtnActionPerformed

    private void viewDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsBtnActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = enterpriseAdminTable.getSelectedRow();
        
        if (selectedRow >= 0) {
            UserAccount ua = (UserAccount) enterpriseAdminTable.getValueAt(selectedRow, 4);
            Enterprise enterprise = (Enterprise) enterpriseAdminTable.getValueAt(selectedRow, 1);
            
            ViewEnterpriseAdminDetailsJPanel viewEnterpriseAdminDetailPanel = new ViewEnterpriseAdminDetailsJPanel(userProcessContainer, enterprise, ua, this);
            userProcessContainer.add("viewEnterpriseAdminDetailPanel", viewEnterpriseAdminDetailPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a row to view details!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_viewDetailsBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    public boolean validateInput() {
        String fname = firstNameTxt.getText().trim();
        String lname = lastNameTxt.getText().trim();
        String cnum = contactNoTxt.getText().trim();
        String uname = usernameTxt.getText().trim();
        String pwd = String.valueOf(pwdTxt.getPassword());
        
        if (fname.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter First Name!", "Error", JOptionPane.ERROR_MESSAGE);
            firstNameTxt.requestFocus();
            return false;
        }
        else if (lname.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter Last Name!", "Error", JOptionPane.ERROR_MESSAGE);
            lastNameTxt.requestFocus();
            return false;
        }
        else if (cnum.isEmpty() || !(cnum.matches("^[0-9]{10}"))) {
            JOptionPane.showMessageDialog(null, "Please enter 10 digits in Contact No.!", "Error", JOptionPane.ERROR_MESSAGE);
            contactNoTxt.requestFocus();
            return false;
        }
        else if (!maleRadioBtn.isSelected() && !femaleRadioBtn.isSelected()) {
            JOptionPane.showMessageDialog(null, "Please select Gender!", "Error", JOptionPane.ERROR_MESSAGE);
            maleRadioBtn.requestFocus();
            return false;
        }
        else if (uname.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter User Name!", "Error", JOptionPane.ERROR_MESSAGE);
            usernameTxt.requestFocus();
            return false;
        }
        else if (HelperMethods.checkIfUserNameExists(uname, system)) {
            JOptionPane.showMessageDialog(null, "Username already exists!", "Error", JOptionPane.ERROR_MESSAGE);
            usernameTxt.requestFocus();
            return false;
        }
        else if (pwd.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter Password!", "Error", JOptionPane.ERROR_MESSAGE);
            firstNameTxt.requestFocus();
            return false;
        }
        else {
            return true;
        }
    }
    
    public void refresh() {
        firstNameTxt.setText("");
        lastNameTxt.setText("");
        contactNoTxt.setText("");
        maleRadioBtn.setSelected(false);
        femaleRadioBtn.setSelected(false);
        usernameTxt.setText("");
        pwdTxt.setText("");
        
        populateEnterpriseAdminTable();
        bindEnterpriseCombo();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEnterpriseAdminBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel contactNoLbl;
    private javax.swing.JTextField contactNoTxt;
    private javax.swing.JButton deleteAdminBtn;
    private javax.swing.JLabel enterpriseAdminLbl;
    private javax.swing.JTable enterpriseAdminTable;
    private javax.swing.JComboBox enterpriseCombo;
    private javax.swing.JLabel errorMsgLbl;
    private javax.swing.JRadioButton femaleRadioBtn;
    private javax.swing.JLabel firstNameLbl;
    private javax.swing.JTextField firstNameTxt;
    private javax.swing.JLabel genderLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameLbl;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JRadioButton maleRadioBtn;
    private javax.swing.JLabel networkLbl;
    private javax.swing.JLabel networkNameLbl;
    private javax.swing.JLabel pwdLbl;
    private javax.swing.JPasswordField pwdTxt;
    private javax.swing.JLabel selectEnterpriseLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JTextField usernameTxt;
    private javax.swing.JButton viewDetailsBtn;
    // End of variables declaration//GEN-END:variables
}
