/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.networkadminrole;

import business.HelperMethods;
import business.enterprise.Enterprise;
import business.enterprise.Enterprise.EnterpriseType;
import business.network.Network;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JAHNVI
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Network network;
    private NetworkAdminWorkAreaJPanel networkAdminPanel;
    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageEnterpriseJPanel() {
        initComponents();
    }

    public ManageEnterpriseJPanel(JPanel userProcessContainer, Network network, NetworkAdminWorkAreaJPanel networkAdminPanel) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.networkAdminPanel = networkAdminPanel;
        networkNameLbl.setText(network.getOrganizationName());
        
        populateEnterpriseTable(network.getEnterpriseDirectory().getEnterpriseList());
        bindEnterpriseTypeCombo();
    }
    
    public void populateEnterpriseTable(ArrayList<Enterprise> enterpriseList) {
        DefaultTableModel dtm = (DefaultTableModel) enterpriseTable.getModel();
        dtm.setRowCount(0);
        
        for (Enterprise enterprise : enterpriseList) {
            Object row[] = new Object[3];
            row[0] = enterprise.getOrganizationId();
            row[1] = enterprise;
            row[2] = enterprise.getEnterpriseType().getValue();
            
            dtm.addRow(row);
        }
    }
    
    public void bindEnterpriseTypeCombo() {
        enterpriseTypeCombo.removeAllItems();
        
        for (EnterpriseType type : EnterpriseType.values()) {
            enterpriseTypeCombo.addItem(type);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        networkLbl = new javax.swing.JLabel();
        networkNameLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseTable = new javax.swing.JTable();
        enterpriseLbl = new javax.swing.JLabel();
        searchLbl = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        enterpriseTypeLbl = new javax.swing.JLabel();
        enterpriseTypeCombo = new javax.swing.JComboBox();
        nameLbl = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        addEnterpriseBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(740, 670));

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 102, 102));
        titleLbl.setText("Network Admin - Manage Enterprise");

        networkLbl.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        networkLbl.setForeground(new java.awt.Color(0, 102, 102));
        networkLbl.setText("Network:");

        networkNameLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        networkNameLbl.setForeground(new java.awt.Color(0, 102, 102));
        networkNameLbl.setText("<Network>");

        jScrollPane1.setForeground(new java.awt.Color(0, 102, 102));

        enterpriseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Enterprise Id", "Enterprise Name", "Enterprise Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(enterpriseTable);
        if (enterpriseTable.getColumnModel().getColumnCount() > 0) {
            enterpriseTable.getColumnModel().getColumn(0).setResizable(false);
            enterpriseTable.getColumnModel().getColumn(1).setResizable(false);
            enterpriseTable.getColumnModel().getColumn(2).setResizable(false);
        }

        enterpriseLbl.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        enterpriseLbl.setForeground(new java.awt.Color(0, 102, 102));
        enterpriseLbl.setText("Enterprise:");

        searchLbl.setForeground(new java.awt.Color(0, 102, 102));
        searchLbl.setText("Enter Enterprise Name to Search:");

        searchTxt.setForeground(new java.awt.Color(0, 102, 102));

        searchBtn.setBackground(new java.awt.Color(153, 153, 153));
        searchBtn.setForeground(new java.awt.Color(0, 102, 102));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(153, 153, 153));
        clearBtn.setForeground(new java.awt.Color(0, 102, 102));
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(153, 153, 153));
        deleteBtn.setForeground(new java.awt.Color(0, 102, 102));
        deleteBtn.setText("Delete Enterprise");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        enterpriseTypeLbl.setForeground(new java.awt.Color(0, 102, 102));
        enterpriseTypeLbl.setText("Enterprise Type:");

        enterpriseTypeCombo.setForeground(new java.awt.Color(0, 102, 102));
        enterpriseTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        nameLbl.setForeground(new java.awt.Color(0, 102, 102));
        nameLbl.setText("Name:");

        nameTxt.setForeground(new java.awt.Color(0, 102, 102));

        addEnterpriseBtn.setBackground(new java.awt.Color(153, 153, 153));
        addEnterpriseBtn.setForeground(new java.awt.Color(0, 102, 102));
        addEnterpriseBtn.setText("Add Enterprise");
        addEnterpriseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEnterpriseBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(153, 153, 153));
        backBtn.setForeground(new java.awt.Color(0, 102, 102));
        backBtn.setText("<<  Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLbl)
                .addGap(226, 226, 226))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(enterpriseLbl))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(deleteBtn)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(searchLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(searchBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clearBtn))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(nameLbl)
                                            .addComponent(enterpriseTypeLbl))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(enterpriseTypeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(228, 228, 228))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(addEnterpriseBtn)
                                        .addGap(148, 148, 148))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(networkLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(networkNameLbl)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(titleLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(networkLbl)
                    .addComponent(networkNameLbl))
                .addGap(61, 61, 61)
                .addComponent(enterpriseLbl)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLbl)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn)
                    .addComponent(clearBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteBtn)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseTypeLbl)
                    .addComponent(enterpriseTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLbl)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(addEnterpriseBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(51, 51, 51))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = enterpriseTable.getSelectedRow();
        
        if (selectedRow >= 0) {
            int confirmButton = JOptionPane.YES_NO_OPTION;
            
            int confirmDelete = JOptionPane.showConfirmDialog(null, "Would you like to delete selected network?", "Warning", confirmButton);
            
            if (confirmDelete == JOptionPane.YES_OPTION) {
                Enterprise enterprise = (Enterprise) enterpriseTable.getValueAt(selectedRow, 1);
                network.getEnterpriseDirectory().deleteEnterprise(enterprise);
                
                populateEnterpriseTable(network.getEnterpriseDirectory().getEnterpriseList());
            }           
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a row to delete an Enterprise!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void addEnterpriseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEnterpriseBtnActionPerformed
        // TODO add your handling code here:
        if (validateInput()) {
            Enterprise enterprise = network.getEnterpriseDirectory().createEnterprise(nameTxt.getText().trim(), EnterpriseType.Community);
            
            if (enterprise != null) {
                JOptionPane.showMessageDialog(null, "Enterprise created successfully!", "Information", JOptionPane.INFORMATION_MESSAGE);
                refresh(network.getEnterpriseDirectory().getEnterpriseList());
            }
        }
    }//GEN-LAST:event_addEnterpriseBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String searchInput = searchTxt.getText().trim();
        
        if (!searchInput.isEmpty()) {
            ArrayList<Enterprise> enterprises = network.getEnterpriseDirectory().searchEnterprise(searchInput);
            
            if (enterprises.size() > 0) {
                populateEnterpriseTable(enterprises);
            } 
            else {
                JOptionPane.showMessageDialog(null, "No such enterprise exists!", "Error", JOptionPane.ERROR_MESSAGE);
                refresh(network.getEnterpriseDirectory().getEnterpriseList());
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please enter Enterprise Name to perform Search!", "Warning", JOptionPane.WARNING_MESSAGE);
            searchTxt.requestFocus();
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        refresh(network.getEnterpriseDirectory().getEnterpriseList());
    }//GEN-LAST:event_clearBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        networkAdminPanel.displayDetails();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    public boolean validateInput() {
        
        String name = nameTxt.getText().trim();
        
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter Enterprise Name!", "Error", JOptionPane.ERROR_MESSAGE);
            nameTxt.requestFocus();
            return false;
        }
        else if (HelperMethods.isEnterpriseExisting(name, network.getEnterpriseDirectory())) {
            JOptionPane.showMessageDialog(null, "Enterprise with same Name already exists!", "Error", JOptionPane.ERROR_MESSAGE);
            nameTxt.requestFocus();
            return false;
        }
        else if (enterpriseTypeCombo.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(null, "Please select Enterprise Type!", "Error", JOptionPane.ERROR_MESSAGE);
            enterpriseTypeCombo.requestFocus();
            return false;
        }
        else {
            return true;
        }
    }
    
    public void refresh(ArrayList<Enterprise> enterpriseList) {
        nameTxt.setText("");
        searchTxt.setText("");
        bindEnterpriseTypeCombo();
        populateEnterpriseTable(enterpriseList);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEnterpriseBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel enterpriseLbl;
    private javax.swing.JTable enterpriseTable;
    private javax.swing.JComboBox enterpriseTypeCombo;
    private javax.swing.JLabel enterpriseTypeLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel networkLbl;
    private javax.swing.JLabel networkNameLbl;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel searchLbl;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
