/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.networkadminrole;

import business.EcoSystem;
import business.network.Network;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author JAHNVI
 */
public class NetworkAdminWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private Network network;
    private UserAccount userAccount;
            
    /**
     * Creates new form NetworkAdminWorkAreaJPanel
     */
    public NetworkAdminWorkAreaJPanel() {
        initComponents();
    }

    public NetworkAdminWorkAreaJPanel(JPanel userProcessContainer, EcoSystem system, Network network, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.network = network;
        this.userAccount = userAccount;
        displayDetails();
    }
    
    public void displayDetails() {
        networkNameLbl.setText(network.getOrganizationName());
        welcomeMsgLbl.setText(welcomeMsgLbl.getText().replace("<Name>", userAccount.getPerson().getFirstName() + " " + userAccount.getPerson().getLastName()));
        
        if (network.getEnterpriseDirectory().getEnterpriseList().isEmpty()) {
            manageEnterpriseAdminBtn.setEnabled(false);
            generateReportsBtn.setEnabled(false);
        }
        else {
            manageEnterpriseAdminBtn.setEnabled(true);
            generateReportsBtn.setEnabled(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        welcomeMsgLbl = new javax.swing.JLabel();
        manageEnterpriseBtn = new javax.swing.JButton();
        manageEnterpriseAdminBtn = new javax.swing.JButton();
        generateReportsBtn = new javax.swing.JButton();
        networkLbl = new javax.swing.JLabel();
        networkNameLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(740, 680));

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 102, 102));
        titleLbl.setText("Network Admin - Work Area");

        welcomeMsgLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        welcomeMsgLbl.setForeground(new java.awt.Color(0, 102, 102));
        welcomeMsgLbl.setText("Welcome, <Name>!");

        manageEnterpriseBtn.setBackground(new java.awt.Color(153, 153, 153));
        manageEnterpriseBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        manageEnterpriseBtn.setForeground(new java.awt.Color(0, 102, 102));
        manageEnterpriseBtn.setText("Manage Enterprise");
        manageEnterpriseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseBtnActionPerformed(evt);
            }
        });

        manageEnterpriseAdminBtn.setBackground(new java.awt.Color(153, 153, 153));
        manageEnterpriseAdminBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        manageEnterpriseAdminBtn.setForeground(new java.awt.Color(0, 102, 102));
        manageEnterpriseAdminBtn.setText("Manage Enterprise Admin");
        manageEnterpriseAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseAdminBtnActionPerformed(evt);
            }
        });

        generateReportsBtn.setBackground(new java.awt.Color(153, 153, 153));
        generateReportsBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        generateReportsBtn.setForeground(new java.awt.Color(0, 102, 102));
        generateReportsBtn.setText("Generate Reports");

        networkLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        networkLbl.setForeground(new java.awt.Color(0, 102, 102));
        networkLbl.setText("Network:");

        networkNameLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        networkNameLbl.setForeground(new java.awt.Color(0, 102, 102));
        networkNameLbl.setText("<Network>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manageEnterpriseAdminBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageEnterpriseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(generateReportsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(titleLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(networkLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(networkNameLbl)))
                .addGap(275, 275, 275))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(welcomeMsgLbl)
                .addGap(217, 217, 217))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(titleLbl)
                .addGap(43, 43, 43)
                .addComponent(welcomeMsgLbl)
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(networkLbl)
                    .addComponent(networkNameLbl))
                .addGap(56, 56, 56)
                .addComponent(manageEnterpriseBtn)
                .addGap(38, 38, 38)
                .addComponent(manageEnterpriseAdminBtn)
                .addGap(38, 38, 38)
                .addComponent(generateReportsBtn)
                .addContainerGap(248, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageEnterpriseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseBtnActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseJPanel manageEnterprisePanel = new ManageEnterpriseJPanel(userProcessContainer, network, this);
        userProcessContainer.add("manageEnterprisePanel", manageEnterprisePanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEnterpriseBtnActionPerformed

    private void manageEnterpriseAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseAdminBtnActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseAdminJPanel manageEnterpriseAdminPanel = new ManageEnterpriseAdminJPanel(userProcessContainer, system, network);
        userProcessContainer.add("manageEnterpriseAdminPanel", manageEnterpriseAdminPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEnterpriseAdminBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generateReportsBtn;
    private javax.swing.JButton manageEnterpriseAdminBtn;
    private javax.swing.JButton manageEnterpriseBtn;
    private javax.swing.JLabel networkLbl;
    private javax.swing.JLabel networkNameLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel welcomeMsgLbl;
    // End of variables declaration//GEN-END:variables
}
