/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.systemadminrole;

import business.EcoSystem;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author JAHNVI
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount userAccount;
    
    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    public SystemAdminWorkAreaJPanel() {
        initComponents();
    }
    
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer, EcoSystem system, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.userAccount = userAccount;
        displayDetails();
    }

    public void displayDetails() {
        sysadminLbl.setText(sysadminLbl.getText().replaceAll("<Name>", userAccount.getPerson().getFirstName() + " " + userAccount.getPerson().getLastName()));
        
        if (system.getNetworkList().getNetworkList().isEmpty()) {
            manageNetworkAdminBtn.setEnabled(false);
        }
        else {
            manageNetworkAdminBtn.setEnabled(true);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        manageNetworkBtn = new javax.swing.JButton();
        manageNetworkAdminBtn = new javax.swing.JButton();
        generateReportsBtn = new javax.swing.JButton();
        sysadminLbl = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 102, 102));
        titleLbl.setText("System Admin - Work Area");

        manageNetworkBtn.setBackground(new java.awt.Color(153, 153, 153));
        manageNetworkBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        manageNetworkBtn.setForeground(new java.awt.Color(0, 102, 102));
        manageNetworkBtn.setText("Manage Network");
        manageNetworkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkBtnActionPerformed(evt);
            }
        });

        manageNetworkAdminBtn.setBackground(new java.awt.Color(153, 153, 153));
        manageNetworkAdminBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        manageNetworkAdminBtn.setForeground(new java.awt.Color(0, 102, 102));
        manageNetworkAdminBtn.setText("Manage Network Admin");
        manageNetworkAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkAdminBtnActionPerformed(evt);
            }
        });

        generateReportsBtn.setBackground(new java.awt.Color(153, 153, 153));
        generateReportsBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        generateReportsBtn.setForeground(new java.awt.Color(0, 102, 102));
        generateReportsBtn.setText("Generate Reports");
        generateReportsBtn.setEnabled(false);

        sysadminLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sysadminLbl.setForeground(new java.awt.Color(0, 102, 102));
        sysadminLbl.setText(" <Name>!");

        welcomeLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        welcomeLbl.setForeground(new java.awt.Color(0, 102, 102));
        welcomeLbl.setText("Welcome,");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titleLbl)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(welcomeLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sysadminLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manageNetworkBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageNetworkAdminBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(generateReportsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(144, 144, 144))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(titleLbl)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sysadminLbl)
                    .addComponent(welcomeLbl))
                .addGap(101, 101, 101)
                .addComponent(manageNetworkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(manageNetworkAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(generateReportsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageNetworkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkBtnActionPerformed
        // TODO add your handling code here:
        ManageNetworkJPanel manageNetworkPanel = new ManageNetworkJPanel(userProcessContainer, system, this);
        userProcessContainer.add("manageNetworkPanel", manageNetworkPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageNetworkBtnActionPerformed

    private void manageNetworkAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkAdminBtnActionPerformed
        // TODO add your handling code here:
        ManageNetworkAdminJPanel manageNetworkAdminPanel = new ManageNetworkAdminJPanel(userProcessContainer, system);
        userProcessContainer.add("manageNetworkAdminPanel", manageNetworkAdminPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageNetworkAdminBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generateReportsBtn;
    private javax.swing.JButton manageNetworkAdminBtn;
    private javax.swing.JButton manageNetworkBtn;
    private javax.swing.JLabel sysadminLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
