/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.householdorganizationadminrole;

import business.EcoSystem;
import business.enterprise.Enterprise;
import business.organization.HouseHoldOrganization;
import business.organization.Organization;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author JAHNVI
 */
public class HouseHoldOrganizationWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private Enterprise enterprise;
    private Organization organization;
    private HouseHoldOrganization houseOrg;
    private UserAccount userAccount;
    /**
     * Creates new form HouseHoldOrganizationWorkAreaJPanel
     */
    public HouseHoldOrganizationWorkAreaJPanel() {
        initComponents();
    }
    
    public HouseHoldOrganizationWorkAreaJPanel(JPanel userProcessContainer, EcoSystem system, Enterprise enterprise, Organization organization, UserAccount ua) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userAccount = ua;
        this.houseOrg = (HouseHoldOrganization) organization;
        displayDetails();
    }

    public void displayDetails() {
        welcomeMsg.setText(welcomeMsg.getText().replace("<Name>", userAccount.getPerson().getFirstName() + " " + userAccount.getPerson().getLastName()));
        
        if (houseOrg.getHouseHoldDirectory().getHouseHoldDirectory().isEmpty()) {
            manageFamilyMemBtn.setEnabled(false);
            generateReportsBtn.setEnabled(false);
        }
        else {
            manageFamilyMemBtn.setEnabled(true);
            generateReportsBtn.setEnabled(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titelLbl = new javax.swing.JLabel();
        welcomeMsg = new javax.swing.JLabel();
        manageHouseHoldBtn = new javax.swing.JButton();
        manageFamilyMemBtn = new javax.swing.JButton();
        generateReportsBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(740, 670));

        titelLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titelLbl.setForeground(new java.awt.Color(0, 102, 102));
        titelLbl.setText("House Hold Organization Admin - Work Area");

        welcomeMsg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        welcomeMsg.setForeground(new java.awt.Color(0, 102, 102));
        welcomeMsg.setText("Welcome, <Name>!");

        manageHouseHoldBtn.setBackground(new java.awt.Color(153, 153, 153));
        manageHouseHoldBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        manageHouseHoldBtn.setForeground(new java.awt.Color(0, 102, 102));
        manageHouseHoldBtn.setText("Manage House Hold");
        manageHouseHoldBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageHouseHoldBtnActionPerformed(evt);
            }
        });

        manageFamilyMemBtn.setBackground(new java.awt.Color(153, 153, 153));
        manageFamilyMemBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        manageFamilyMemBtn.setForeground(new java.awt.Color(0, 102, 102));
        manageFamilyMemBtn.setText("Manage Family Members");
        manageFamilyMemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageFamilyMemBtnActionPerformed(evt);
            }
        });

        generateReportsBtn.setBackground(new java.awt.Color(153, 153, 153));
        generateReportsBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        generateReportsBtn.setForeground(new java.awt.Color(0, 102, 102));
        generateReportsBtn.setText("Generate Reports");
        generateReportsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(welcomeMsg)
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titelLbl)
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manageFamilyMemBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageHouseHoldBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(generateReportsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(269, 269, 269))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titelLbl)
                .addGap(33, 33, 33)
                .addComponent(welcomeMsg)
                .addGap(140, 140, 140)
                .addComponent(manageHouseHoldBtn)
                .addGap(43, 43, 43)
                .addComponent(manageFamilyMemBtn)
                .addGap(45, 45, 45)
                .addComponent(generateReportsBtn)
                .addContainerGap(274, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageHouseHoldBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageHouseHoldBtnActionPerformed
        // TODO add your handling code here:
        ManageHouseHoldJPanel manageHouseHoldPanel = new ManageHouseHoldJPanel(userProcessContainer, system, organization, this);
        userProcessContainer.add("manageHouseHoldPanel", manageHouseHoldPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageHouseHoldBtnActionPerformed

    private void manageFamilyMemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageFamilyMemBtnActionPerformed
        // TODO add your handling code here:
        ManageFamilyMembersJPanel manageFamilyMemberPanel = new ManageFamilyMembersJPanel(userProcessContainer, system, organization);
        userProcessContainer.add("manageFamilyMemberPanel", manageFamilyMemberPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageFamilyMemBtnActionPerformed

    private void generateReportsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportsBtnActionPerformed
        // TODO add your handling code here:
        GenerateHouseHoldOrgReportsJPanel generateHouseOrgReportsJPanel = new GenerateHouseHoldOrgReportsJPanel(userProcessContainer, enterprise, organization, userAccount);
        userProcessContainer.add("generateHouseOrgReportsJPanel", generateHouseOrgReportsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_generateReportsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generateReportsBtn;
    private javax.swing.JButton manageFamilyMemBtn;
    private javax.swing.JButton manageHouseHoldBtn;
    private javax.swing.JLabel titelLbl;
    private javax.swing.JLabel welcomeMsg;
    // End of variables declaration//GEN-END:variables
}
