/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.householdorganizationadminrole;

import business.data.FoodConsumptionDetail;
import business.data.VitalSign;
import business.household.HouseHold;
import business.organization.HouseHoldOrganization;
import business.person.FamilyMember;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.ItemLabelAnchor;
import org.jfree.chart.labels.ItemLabelPosition;
import org.jfree.chart.labels.StandardCategoryItemLabelGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.ui.TextAnchor;

/**
 *
 * @author JAHNVI
 */
public class ViewFamilyNutrientTrendsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private HouseHoldOrganization houseOrg;
    private UserAccount userAccount;
    private ArrayList<FamilyMember> members;
    
    /**
     * Creates new form ViewFamilyNutrientTrendsJPanel
     */
    public ViewFamilyNutrientTrendsJPanel() {
        initComponents();
    }
    
    public ViewFamilyNutrientTrendsJPanel(JPanel userProcessContainer, HouseHoldOrganization houseOrg, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.houseOrg = houseOrg;
        this.userAccount = userAccount;
        displayDetails();
    }

    public void displayDetails() {
        welcomeNameLbl.setText(welcomeNameLbl.getText().replace("<Name>", userAccount.getPerson().getFirstName() + " " + userAccount.getPerson().getLastName()));
        bindHouseCombo();
    }

    public void bindHouseCombo() {
        houseHoldCombo.removeAllItems();
        
        for (HouseHold house : houseOrg.getHouseHoldDirectory().getHouseHoldDirectory()) {
            houseHoldCombo.addItem(house);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectHouseHoldLbl = new javax.swing.JLabel();
        houseHoldCombo = new javax.swing.JComboBox();
        welcomeLbl = new javax.swing.JLabel();
        welcomeNameLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        viewTrendsBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(740, 670));

        selectHouseHoldLbl.setForeground(new java.awt.Color(0, 102, 102));
        selectHouseHoldLbl.setText("Select House Hold:");

        houseHoldCombo.setForeground(new java.awt.Color(0, 102, 102));
        houseHoldCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        houseHoldCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                houseHoldComboActionPerformed(evt);
            }
        });

        welcomeLbl.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        welcomeLbl.setForeground(new java.awt.Color(0, 102, 102));
        welcomeLbl.setText("Welcome,");

        welcomeNameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        welcomeNameLbl.setForeground(new java.awt.Color(0, 102, 102));
        welcomeNameLbl.setText("<Name>!");

        backBtn.setBackground(new java.awt.Color(153, 153, 153));
        backBtn.setForeground(new java.awt.Color(0, 102, 102));
        backBtn.setText("<<  Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 102, 102));
        titleLbl.setText("House Hould Organization Admin - View Family Nutirent Trends");

        viewTrendsBtn.setBackground(new java.awt.Color(153, 153, 153));
        viewTrendsBtn.setForeground(new java.awt.Color(0, 102, 102));
        viewTrendsBtn.setText("View Trends");
        viewTrendsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTrendsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLbl)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(welcomeLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(welcomeNameLbl)
                        .addGap(26, 26, 26)))
                .addGap(128, 128, 128))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectHouseHoldLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(houseHoldCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(viewTrendsBtn)))
                .addGap(243, 243, 243))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(backBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(titleLbl)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcomeLbl)
                    .addComponent(welcomeNameLbl))
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectHouseHoldLbl)
                    .addComponent(houseHoldCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(viewTrendsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void houseHoldComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_houseHoldComboActionPerformed
        // TODO add your handling code here:
        HouseHold house = (HouseHold) houseHoldCombo.getSelectedItem();

        if (house != null) {
            members = (ArrayList) house.getFamilyMembers().getPersonList();
        }
    }//GEN-LAST:event_houseHoldComboActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void viewTrendsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTrendsBtnActionPerformed
        // TODO add your handling code here:
        generateReport(members);
    }//GEN-LAST:event_viewTrendsBtnActionPerformed

    public void generateReport(ArrayList<FamilyMember> membersList) {
       
        for (FamilyMember member : membersList) {
            DefaultCategoryDataset dataset = new DefaultCategoryDataset();
            
            for (FoodConsumptionDetail fcd : member.getFoodConsumptionHistory().getFoodConsumptionDetailHistory()) {
                Double energy = Double.parseDouble(String.valueOf(fcd.getEnergy()));
                Double protien = Double.parseDouble(String.valueOf(fcd.getProtien()));
                Double fat = Double.parseDouble(String.valueOf(fcd.getFat()));
                Double carbo = Double.parseDouble(String.valueOf(fcd.getCarbohydrates()));
                Double fibers = Double.parseDouble(String.valueOf(fcd.getFibers()));
                Double sugar = Double.parseDouble(String.valueOf(fcd.getSugar()));
                Double salt = Double.parseDouble(String.valueOf(fcd.getSalt()));
                Double iodine = Double.parseDouble(String.valueOf(fcd.getIodine()));
                Double vitA = Double.parseDouble(String.valueOf(fcd.getVitaminA()));
                Double vitB12 = Double.parseDouble(String.valueOf(fcd.getVitaminB12()));
                Double vitC = Double.parseDouble(String.valueOf(fcd.getVitaminC()));
                Double vitD = Double.parseDouble(String.valueOf(fcd.getVitaminD()));
                Double vitE = Double.parseDouble(String.valueOf(fcd.getVitaminE()));
                Double vitK = Double.parseDouble(String.valueOf(fcd.getVitaminK()));
            
                dataset.addValue(energy, "Energy", fcd.getTimestamp());
                dataset.addValue(protien, "Protien", fcd.getTimestamp());
                dataset.addValue(fat, "Fat", fcd.getTimestamp());
                dataset.addValue(carbo, "Carbohydrates", fcd.getTimestamp());
                dataset.addValue(fibers, "Fibers", fcd.getTimestamp());
                dataset.addValue(sugar, "Sugar", fcd.getTimestamp());
                dataset.addValue(salt, "Salt", fcd.getTimestamp());
                dataset.addValue(iodine, "Iodine", fcd.getTimestamp());
                dataset.addValue(vitA, "Vitamin A", fcd.getTimestamp());
                dataset.addValue(vitB12, "Vitamin B12", fcd.getTimestamp());
                dataset.addValue(vitC, "Vitamin C", fcd.getTimestamp());
                dataset.addValue(vitD, "VItamin D", fcd.getTimestamp());
                dataset.addValue(vitE, "Vitamin E", fcd.getTimestamp());
                dataset.addValue(vitK, "Vitamin K", fcd.getTimestamp());            
            }
            
            JFreeChart chart = ChartFactory.createLineChart(member.getFirstName() + "'s Nutrient Trend", "Nutrients", "Values", dataset);
            
            final CategoryPlot plot = chart.getCategoryPlot();
        
            LineAndShapeRenderer renderer = (LineAndShapeRenderer) plot.getRenderer();
            DecimalFormat decimalFormat = new DecimalFormat("####.##");
            renderer.setShapesVisible(true);
            renderer.setItemLabelGenerator(new StandardCategoryItemLabelGenerator("{2}", decimalFormat));
            plot.setRenderer(renderer);
            renderer.setPositiveItemLabelPosition(new ItemLabelPosition(ItemLabelAnchor.OUTSIDE12, TextAnchor.HALF_ASCENT_CENTER));
            renderer.setItemLabelsVisible(true);
            chart.getCategoryPlot().setRenderer(renderer);
            
            JFrame frame = new JFrame("Nutrient Trends For The Family");
            frame.getContentPane().add(new ChartPanel(chart));
          
            frame.pack();
            frame.setVisible(true);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox houseHoldCombo;
    private javax.swing.JLabel selectHouseHoldLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JButton viewTrendsBtn;
    private javax.swing.JLabel welcomeLbl;
    private javax.swing.JLabel welcomeNameLbl;
    // End of variables declaration//GEN-END:variables
}
