/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import business.EcoSystem;
import business.db4outil.DB4OUtil;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.Organization;
import business.organization.StoreOrganization;
import business.store.Store;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author JAHNVI
 */
public class MainJFrame extends javax.swing.JFrame {

    private EcoSystem system;
    private DB4OUtil db4oUtil = DB4OUtil.getInstance();
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        system = db4oUtil.retrieveSystem();
        setWelcomJPanel();
    }

    public void setWelcomJPanel() {
        WelcomeJPanel welcome = new WelcomeJPanel();
        userProcessContainer.add("welcomPanel", welcome);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSplitPane = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        logInLbl = new javax.swing.JLabel();
        usernameLbl = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        pwdLbl = new javax.swing.JLabel();
        pwdTxt = new javax.swing.JPasswordField();
        logInBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftPanel.setBackground(new java.awt.Color(0, 102, 102));

        logInLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logInLbl.setForeground(new java.awt.Color(204, 204, 204));
        logInLbl.setText("User Log In:");

        usernameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usernameLbl.setForeground(new java.awt.Color(204, 204, 204));
        usernameLbl.setText("User Name:");

        pwdLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pwdLbl.setForeground(new java.awt.Color(204, 204, 204));
        pwdLbl.setText("Password:");

        logInBtn.setBackground(new java.awt.Color(153, 153, 153));
        logInBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logInBtn.setForeground(new java.awt.Color(0, 102, 102));
        logInBtn.setText("Log In");
        logInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInBtnActionPerformed(evt);
            }
        });

        logOutBtn.setBackground(new java.awt.Color(153, 153, 153));
        logOutBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logOutBtn.setForeground(new java.awt.Color(0, 153, 153));
        logOutBtn.setText("Log Out");
        logOutBtn.setEnabled(false);
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameLbl)
                            .addComponent(pwdLbl))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(usernameTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pwdTxt)
                    .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                            .addComponent(logInLbl)
                            .addGap(9, 9, 9))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                            .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(logInBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10))))
                .addContainerGap())
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(logInLbl)
                .addGap(18, 18, 18)
                .addComponent(usernameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(pwdLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(logInBtn)
                .addGap(18, 18, 18)
                .addComponent(logOutBtn)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        mainSplitPane.setLeftComponent(leftPanel);

        userProcessContainer.setBackground(new java.awt.Color(204, 204, 204));
        userProcessContainer.setPreferredSize(new java.awt.Dimension(750, 680));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        mainSplitPane.setRightComponent(userProcessContainer);

        getContentPane().add(mainSplitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInBtnActionPerformed
        // TODO add your handling code here:
        String username = usernameTxt.getText();
        String password = String.valueOf(pwdTxt.getPassword());
        
        UserAccount userAccount = system.getUserAccountDirectory().authenticateUser(username, password);
        Network inNetwork = null;
        Enterprise inEnterprise = null;
        Organization inOrganization = null;
        Store inStore = null;
        
        if (userAccount == null) {
            for(Network network : system.getNetworkList().getNetworkList()) {
                userAccount = network.getUserAccountDirectory().authenticateUser(username, password);
                
                if(userAccount == null) {
                    for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                        userAccount = enterprise.getUserAccountDirectory().authenticateUser(username, password);
                        
                        if (userAccount == null) {
                            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                                userAccount = organization.getUserAccountDirectory().authenticateUser(username, password);
                                
                                if (userAccount != null) {
                                    inNetwork = network;
                                    inEnterprise = enterprise;
                                    inOrganization = organization;
                                    break;
                                }
                                else {
                                    if (organization instanceof StoreOrganization) {
                                        StoreOrganization org = (StoreOrganization) organization;
                                        for (Store store : org.getStoreDirectory().getStoreList()) {
                                            userAccount = store.getUserAccountDirectory().authenticateUser(username, password);
                                        
                                            if (userAccount != null) {
                                                inNetwork = network;
                                                inEnterprise = enterprise;
                                                inOrganization = organization;
                                                inStore = store;
                                                break;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                        else {
                            inNetwork = network;
                            inEnterprise = enterprise;
                            break;
                        }
                        if (inOrganization != null) {
                            break;
                        }
                    }
                }
                else {
                    inNetwork = network;
                    break;
                }
                if (inEnterprise != null) {
                    break;
                }
            }
        }
        
        if (userAccount == null) {
            JOptionPane.showMessageDialog(null, "Invalid Credentials!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else {
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("workArea", userAccount.getRole().createWorkArea(userProcessContainer, system, inNetwork, inEnterprise, inOrganization, inStore, userAccount));
            layout.next(userProcessContainer);
        }
        
        usernameTxt.setEnabled(false);
        pwdTxt.setEnabled(false);
        logInBtn.setEnabled(false);
        logOutBtn.setEnabled(true);
    }//GEN-LAST:event_logInBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        // TODO add your handling code here:
        logOutBtn.setEnabled(false);
        logInBtn.setEnabled(true);
        
        usernameTxt.setText("");
        usernameTxt.setEnabled(true);
        pwdTxt.setText("");
        pwdTxt.setEnabled(true);
        
        userProcessContainer.removeAll();
        setWelcomJPanel();
        db4oUtil.storeSystem(system);
    }//GEN-LAST:event_logOutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel leftPanel;
    private javax.swing.JButton logInBtn;
    private javax.swing.JLabel logInLbl;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JSplitPane mainSplitPane;
    private javax.swing.JLabel pwdLbl;
    private javax.swing.JPasswordField pwdTxt;
    private javax.swing.JPanel userProcessContainer;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
