/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.enterpriseradminrole;

import business.EcoSystem;
import business.enterprise.Enterprise;
import business.network.Network;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author JAHNVI
 */
public class EnterpriseAdminWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private Network network;
    private Enterprise enterprise;
    private UserAccount userAccount;
            
    /**
     * Creates new form EnterpriseAdminWorkAreaJPanel
     */
    public EnterpriseAdminWorkAreaJPanel() {
        initComponents();
    }

    public EnterpriseAdminWorkAreaJPanel(JPanel userProcessContainer, EcoSystem system, Network network, Enterprise enterprise, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.network = network;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        displayDetails();
    }

    public void displayDetails() {
        enterpriseNameLbl.setText(enterprise.getOrganizationName());    
        welcomeMsgLbl.setText(welcomeMsgLbl.getText().replace("<Name>", userAccount.getPerson().getFirstName() + " " + userAccount.getPerson().getLastName()));
        
        if (enterprise.getOrganizationDirectory().getOrganizationList().isEmpty()) {
            manageOrgAdminBtn.setEnabled(false);
            generateReportsBtn.setEnabled(false);
        }
        else {
            manageOrgAdminBtn.setEnabled(true);
            generateReportsBtn.setEnabled(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        welcomeMsgLbl = new javax.swing.JLabel();
        enterpriseLbl = new javax.swing.JLabel();
        enterpriseNameLbl = new javax.swing.JLabel();
        manageOrgBtn = new javax.swing.JButton();
        manageOrgAdminBtn = new javax.swing.JButton();
        generateReportsBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(740, 670));

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 102, 102));
        titleLbl.setText("Enterprise Admin - Work Area");

        welcomeMsgLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        welcomeMsgLbl.setForeground(new java.awt.Color(0, 102, 102));
        welcomeMsgLbl.setText("Welcome, <Name>!");

        enterpriseLbl.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        enterpriseLbl.setForeground(new java.awt.Color(0, 102, 102));
        enterpriseLbl.setText("Enterprise:");

        enterpriseNameLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enterpriseNameLbl.setForeground(new java.awt.Color(0, 102, 102));
        enterpriseNameLbl.setText("<Enterprise>");

        manageOrgBtn.setBackground(new java.awt.Color(153, 153, 153));
        manageOrgBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        manageOrgBtn.setForeground(new java.awt.Color(0, 102, 102));
        manageOrgBtn.setText("Manage Organization");
        manageOrgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrgBtnActionPerformed(evt);
            }
        });

        manageOrgAdminBtn.setBackground(new java.awt.Color(153, 153, 153));
        manageOrgAdminBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        manageOrgAdminBtn.setForeground(new java.awt.Color(0, 102, 102));
        manageOrgAdminBtn.setText("Manage Organization Admin");
        manageOrgAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrgAdminBtnActionPerformed(evt);
            }
        });

        generateReportsBtn.setBackground(new java.awt.Color(153, 153, 153));
        generateReportsBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        generateReportsBtn.setForeground(new java.awt.Color(0, 102, 102));
        generateReportsBtn.setText("Generate Reports");
        generateReportsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(titleLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(enterpriseLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(enterpriseNameLbl))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(manageOrgAdminBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(manageOrgBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(generateReportsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(269, 269, 269))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(welcomeMsgLbl)
                .addGap(144, 144, 144))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(titleLbl)
                .addGap(38, 38, 38)
                .addComponent(welcomeMsgLbl)
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLbl)
                    .addComponent(enterpriseNameLbl))
                .addGap(54, 54, 54)
                .addComponent(manageOrgBtn)
                .addGap(36, 36, 36)
                .addComponent(manageOrgAdminBtn)
                .addGap(37, 37, 37)
                .addComponent(generateReportsBtn)
                .addGap(256, 256, 256))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageOrgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrgBtnActionPerformed
        // TODO add your handling code here:
        ManageOrganizationJPanel manageOrgPanel = new ManageOrganizationJPanel(userProcessContainer, enterprise, this);
        userProcessContainer.add("manageOrgPanel", manageOrgPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrgBtnActionPerformed

    private void manageOrgAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrgAdminBtnActionPerformed
        // TODO add your handling code here
        ManageOrganizationAdminJPanel manageOrgAdminPanel = new ManageOrganizationAdminJPanel(userProcessContainer, system, enterprise);
        userProcessContainer.add("manageOrgAdminPanel", manageOrgAdminPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrgAdminBtnActionPerformed

    private void generateReportsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportsBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_generateReportsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLbl;
    private javax.swing.JLabel enterpriseNameLbl;
    private javax.swing.JButton generateReportsBtn;
    private javax.swing.JButton manageOrgAdminBtn;
    private javax.swing.JButton manageOrgBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel welcomeMsgLbl;
    // End of variables declaration//GEN-END:variables
}
