/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.enterpriseradminrole;

import business.enterprise.Enterprise;
import business.organization.Organization;
import business.organization.Organization.OrganizationType;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JAHNVI
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {

    private JPanel userProessContainer;
    private Enterprise enterprise;
    private EnterpriseAdminWorkAreaJPanel enterpriseAdminPanel;
    
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageOrganizationJPanel() {
        initComponents();
    }
    
    public ManageOrganizationJPanel(JPanel userProcessContainer, Enterprise enterprise, EnterpriseAdminWorkAreaJPanel enterpriseAdminPanel) {
        initComponents();
        this.userProessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.enterpriseAdminPanel = enterpriseAdminPanel;
        enterpriseNameLbl.setText(enterprise.getOrganizationName());
        
        populateOrgTable(enterprise.getOrganizationDirectory().getOrganizationList());
        bindOrgTypeCombo();
    }

    public void populateOrgTable(ArrayList<Organization> orgList) {
        DefaultTableModel dtm = (DefaultTableModel) organizationTable.getModel();
        dtm.setRowCount(0);
        
        for (Organization org : orgList) {
            Object row[] = new Object[2];
            row[0] = org.getOrganizationId();
            row[1] = org;
            
            dtm.addRow(row);
        }
    }
    
    public void bindOrgTypeCombo() {
        orgTypeCombo.removeAllItems();
        ArrayList<String> orgList = new ArrayList<>();
        
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            orgList.add(org.getOrganizationName());
        }
        
        for (OrganizationType type: OrganizationType.values()) {
            if (!orgList.contains(type.getValue())) {
                orgTypeCombo.addItem(type);
            }
        }
        
        if (orgTypeCombo.getItemCount() == 0) {
            addOrgBtn.setEnabled(false);
            errorMsgLbl.setText("All types of Organizations are created for the Enterprise!");
            errorMsgLbl.setVisible(true);
        }
        else {
            addOrgBtn.setEnabled(true);
            errorMsgLbl.setVisible(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        enterpriseLbl = new javax.swing.JLabel();
        enterpriseNameLbl = new javax.swing.JLabel();
        orgListLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        organizationTable = new javax.swing.JTable();
        searchLbl = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        deleteOrgBtn = new javax.swing.JButton();
        selectOrgLbl = new javax.swing.JLabel();
        orgTypeCombo = new javax.swing.JComboBox();
        addOrgBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        errorMsgLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(740, 670));

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 102, 102));
        titleLbl.setText("Enterprise Admin - Manage Organization");

        enterpriseLbl.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        enterpriseLbl.setForeground(new java.awt.Color(0, 102, 102));
        enterpriseLbl.setText("Enterprise:");

        enterpriseNameLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enterpriseNameLbl.setForeground(new java.awt.Color(0, 102, 102));
        enterpriseNameLbl.setText("<Enterprise>");

        orgListLbl.setForeground(new java.awt.Color(0, 102, 102));
        orgListLbl.setText("Organization List:");

        jScrollPane1.setForeground(new java.awt.Color(0, 102, 102));

        organizationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Organization Id", "Organization Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(organizationTable);
        if (organizationTable.getColumnModel().getColumnCount() > 0) {
            organizationTable.getColumnModel().getColumn(0).setResizable(false);
            organizationTable.getColumnModel().getColumn(1).setResizable(false);
        }

        searchLbl.setForeground(new java.awt.Color(0, 102, 102));
        searchLbl.setText("Enter Organization Name to Search:");

        searchTxt.setForeground(new java.awt.Color(0, 102, 102));

        searchBtn.setBackground(new java.awt.Color(153, 153, 153));
        searchBtn.setForeground(new java.awt.Color(0, 102, 102));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(153, 153, 153));
        clearBtn.setForeground(new java.awt.Color(0, 102, 102));
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        deleteOrgBtn.setBackground(new java.awt.Color(153, 153, 153));
        deleteOrgBtn.setForeground(new java.awt.Color(0, 102, 102));
        deleteOrgBtn.setText("Delete Organization");
        deleteOrgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteOrgBtnActionPerformed(evt);
            }
        });

        selectOrgLbl.setForeground(new java.awt.Color(0, 102, 102));
        selectOrgLbl.setText("Select Organization Type:");

        orgTypeCombo.setForeground(new java.awt.Color(0, 102, 102));
        orgTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addOrgBtn.setBackground(new java.awt.Color(153, 153, 153));
        addOrgBtn.setForeground(new java.awt.Color(0, 102, 102));
        addOrgBtn.setText("Add Organization");
        addOrgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrgBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(153, 153, 153));
        backBtn.setForeground(new java.awt.Color(0, 102, 102));
        backBtn.setText("<<  Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        errorMsgLbl.setForeground(new java.awt.Color(255, 102, 102));
        errorMsgLbl.setText("<Error Message>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(titleLbl)
                .addGap(206, 206, 206))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(backBtn)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addOrgBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orgListLbl)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(deleteOrgBtn)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(searchLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(searchBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clearBtn))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(selectOrgLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(orgTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)))
                .addGap(128, 128, 128))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(enterpriseLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(enterpriseNameLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(errorMsgLbl)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titleLbl)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLbl)
                    .addComponent(enterpriseNameLbl))
                .addGap(89, 89, 89)
                .addComponent(orgListLbl)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLbl)
                    .addComponent(searchBtn)
                    .addComponent(clearBtn)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteOrgBtn)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectOrgLbl)
                    .addComponent(orgTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addOrgBtn)
                .addGap(25, 25, 25)
                .addComponent(errorMsgLbl)
                .addGap(92, 92, 92)
                .addComponent(backBtn)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String searchInput = searchTxt.getText().trim();

        if (!searchInput.isEmpty()) {
            ArrayList<Organization> orgs = enterprise.getOrganizationDirectory().searchOrganization(searchInput);

            if (orgs.size() > 0) {
                populateOrgTable(orgs);
            }
            else {
                JOptionPane.showMessageDialog(null, "No such organization exists!", "Error", JOptionPane.ERROR_MESSAGE);
                refresh(enterprise.getOrganizationDirectory().getOrganizationList());
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please enter Enterprise Name to perform Search!", "Warning", JOptionPane.WARNING_MESSAGE);
            searchTxt.requestFocus();
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        refresh(enterprise.getOrganizationDirectory().getOrganizationList());
    }//GEN-LAST:event_clearBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
       userProessContainer.remove(this);
       enterpriseAdminPanel.displayDetails();
       CardLayout layout = (CardLayout) userProessContainer.getLayout();
       layout.previous(userProessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void addOrgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrgBtnActionPerformed
        // TODO add your handling code here:
        if (validateInput()) {
            Organization org = enterprise.getOrganizationDirectory().createOrganization((OrganizationType) orgTypeCombo.getSelectedItem());
            
            if (org != null) {
                JOptionPane.showMessageDialog(null, "Organization created successfully!", "Information", JOptionPane.INFORMATION_MESSAGE);
                refresh(enterprise.getOrganizationDirectory().getOrganizationList());
            }
        }
    }//GEN-LAST:event_addOrgBtnActionPerformed

    private void deleteOrgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteOrgBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = organizationTable.getSelectedRow();
        
        if (selectedRow >= 0) {
            int confirmButton = JOptionPane.YES_NO_OPTION;
            
            int confirmDelete = JOptionPane.showConfirmDialog(null, "Would you like to delete selected network?", "Warning", confirmButton);
            
            if (confirmDelete == JOptionPane.YES_OPTION) {
                Organization org = (Organization) organizationTable.getValueAt(selectedRow, 1);
                enterprise.getOrganizationDirectory().deleteOrganization(org);
                
                populateOrgTable(enterprise.getOrganizationDirectory().getOrganizationList());
            }  
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a row to delete organization!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteOrgBtnActionPerformed

    public boolean validateInput() {
        if (orgTypeCombo.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(null, "Please select a type to add organization!", "Error", JOptionPane.ERROR_MESSAGE);
            orgTypeCombo.requestFocus();
            return false;
        }
        else {
            return true;
        }
    }

    public void refresh(ArrayList<Organization> orgList) {
        bindOrgTypeCombo();
        populateOrgTable(orgList);
        searchTxt.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOrgBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton deleteOrgBtn;
    private javax.swing.JLabel enterpriseLbl;
    private javax.swing.JLabel enterpriseNameLbl;
    private javax.swing.JLabel errorMsgLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel orgListLbl;
    private javax.swing.JComboBox orgTypeCombo;
    private javax.swing.JTable organizationTable;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel searchLbl;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JLabel selectOrgLbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
