/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.enterpriseradminrole;

import business.household.HouseHold;
import business.organization.HouseHoldOrganization;
import business.person.FamilyMember;
import business.useraccount.UserAccount;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author JAHNVI
 */
public class ViewHealthiestHouseJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private HouseHoldOrganization houseOrg;
    private UserAccount userAccount;
    /**
     * Creates new form ViewHealthiestHouseJPanel
     */
    public ViewHealthiestHouseJPanel() {
        initComponents();
    }
    
    public ViewHealthiestHouseJPanel(JPanel userProcessContainer, HouseHoldOrganization houseOrg, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.houseOrg = houseOrg;
        this.userAccount = userAccount;
        displayDetails();
    }

    public void displayDetails() {
        welcomeNameLbl.setText(welcomeNameLbl.getText().replace("<Name>", userAccount.getPerson().getFirstName() + userAccount.getPerson().getLastName()));
        
    }
    
    public void findHealthiestHouse() {
        int count = 0;
        int oldCount = 0;
        
        for (HouseHold house : houseOrg.getHouseHoldDirectory().getHouseHoldDirectory()) {
            
            ArrayList<FamilyMember> members = (ArrayList) house.getFamilyMembers().getPersonList();
            
            for (FamilyMember member : members) {
                
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        welcomeNameLbl = new javax.swing.JLabel();
        houseHoldIdLbl = new javax.swing.JLabel();
        houseHoldId = new javax.swing.JLabel();
        houseHoldNameLbl = new javax.swing.JLabel();
        houseHoldName = new javax.swing.JLabel();
        addressLbl = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        familyMembersLbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        familyMembersTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 102, 102));
        titleLbl.setText("House Hould Organization Admin - View Healthiest House");

        welcomeLbl.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        welcomeLbl.setForeground(new java.awt.Color(0, 102, 102));
        welcomeLbl.setText("Welcome,");

        welcomeNameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        welcomeNameLbl.setForeground(new java.awt.Color(0, 102, 102));
        welcomeNameLbl.setText("<Name>!");

        houseHoldIdLbl.setForeground(new java.awt.Color(0, 102, 102));
        houseHoldIdLbl.setText("House Hold Id:");

        houseHoldId.setForeground(new java.awt.Color(0, 102, 102));
        houseHoldId.setText("<House Hold Id>");
        houseHoldId.setEnabled(false);

        houseHoldNameLbl.setForeground(new java.awt.Color(0, 102, 102));
        houseHoldNameLbl.setText("House Hold Name:");

        houseHoldName.setForeground(new java.awt.Color(0, 102, 102));
        houseHoldName.setText("<House Hold Name>");
        houseHoldName.setEnabled(false);

        addressLbl.setForeground(new java.awt.Color(0, 102, 102));
        addressLbl.setText("Address:");

        address.setForeground(new java.awt.Color(0, 102, 102));
        address.setText("<Address>");
        address.setEnabled(false);

        familyMembersLbl.setForeground(new java.awt.Color(0, 102, 102));
        familyMembersLbl.setText("Family Members:");

        jScrollPane2.setForeground(new java.awt.Color(0, 102, 102));

        familyMembersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Date Of Birth", "Is Head of The Family", "User Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(familyMembersTable);

        backBtn.setForeground(new java.awt.Color(0, 102, 102));
        backBtn.setText("<<  Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(welcomeLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeNameLbl)
                .addGap(116, 116, 116))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(houseHoldNameLbl)
                            .addComponent(houseHoldIdLbl)
                            .addComponent(addressLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(houseHoldId)
                            .addComponent(houseHoldName)
                            .addComponent(address)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLbl)
                            .addComponent(familyMembersLbl))))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(backBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(titleLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcomeLbl)
                    .addComponent(welcomeNameLbl))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(houseHoldIdLbl)
                    .addComponent(houseHoldId))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(houseHoldNameLbl)
                    .addComponent(houseHoldName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLbl)
                    .addComponent(address))
                .addGap(28, 28, 28)
                .addComponent(familyMembersLbl)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JLabel addressLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel familyMembersLbl;
    private javax.swing.JTable familyMembersTable;
    private javax.swing.JLabel houseHoldId;
    private javax.swing.JLabel houseHoldIdLbl;
    private javax.swing.JLabel houseHoldName;
    private javax.swing.JLabel houseHoldNameLbl;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel welcomeLbl;
    private javax.swing.JLabel welcomeNameLbl;
    // End of variables declaration//GEN-END:variables
}
