/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.storeadminrole;

import business.store.Product;
import business.store.Store;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JAHNVI
 */
public class ManageProductCatalogJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Store store;
    
    /**
     * Creates new form ManageProductCatalogJPanel
     */
    public ManageProductCatalogJPanel() {
        initComponents();
    }
    
    public ManageProductCatalogJPanel(JPanel userProcessContainer, Store store) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.store = store;
        storeNameDisplayLbl.setText(store.getStoreName());
        populateProdTable();
    }
    
    public void populateProdTable() {
        DefaultTableModel dtm = (DefaultTableModel) productCatalogTable.getModel();
        dtm.setRowCount(0);
        
        for (Product prod : store.getProductCatalog().getProductCatalog()) {
            Object row[] = new Object[5];
            row[0] = prod.getBarcodeNumber();
            row[1] = prod;
            row[2] = prod.getWeight();
            row[3] = prod.getQuantity();
            row[4] = prod.getPrice();
            
            dtm.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        storeNameLbl = new javax.swing.JLabel();
        storeNameDisplayLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productCatalogTable = new javax.swing.JTable();
        prodCatLbl = new javax.swing.JLabel();
        addProdBtn = new javax.swing.JButton();
        deleteProdBtn = new javax.swing.JButton();
        viewDetailsBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 102, 102));
        titleLbl.setText("Store Admin - Manage Product Catalog");

        storeNameLbl.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        storeNameLbl.setForeground(new java.awt.Color(0, 102, 102));
        storeNameLbl.setText("Store Name:");

        storeNameDisplayLbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        storeNameDisplayLbl.setForeground(new java.awt.Color(0, 102, 102));
        storeNameDisplayLbl.setText("<Store Name>");

        jScrollPane1.setForeground(new java.awt.Color(0, 102, 102));

        productCatalogTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Barcode", "Product Name", "Weight", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(productCatalogTable);
        if (productCatalogTable.getColumnModel().getColumnCount() > 0) {
            productCatalogTable.getColumnModel().getColumn(0).setResizable(false);
            productCatalogTable.getColumnModel().getColumn(1).setResizable(false);
            productCatalogTable.getColumnModel().getColumn(2).setResizable(false);
            productCatalogTable.getColumnModel().getColumn(3).setResizable(false);
            productCatalogTable.getColumnModel().getColumn(4).setResizable(false);
        }

        prodCatLbl.setForeground(new java.awt.Color(0, 102, 102));
        prodCatLbl.setText("Product Catalog:");

        addProdBtn.setBackground(new java.awt.Color(153, 153, 153));
        addProdBtn.setForeground(new java.awt.Color(0, 102, 102));
        addProdBtn.setText("Add Product");
        addProdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProdBtnActionPerformed(evt);
            }
        });

        deleteProdBtn.setBackground(new java.awt.Color(153, 153, 153));
        deleteProdBtn.setForeground(new java.awt.Color(0, 102, 102));
        deleteProdBtn.setText("Delete Product");
        deleteProdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProdBtnActionPerformed(evt);
            }
        });

        viewDetailsBtn.setBackground(new java.awt.Color(153, 153, 153));
        viewDetailsBtn.setForeground(new java.awt.Color(0, 102, 102));
        viewDetailsBtn.setText("View Product Details");
        viewDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(153, 153, 153));
        backBtn.setForeground(new java.awt.Color(0, 102, 102));
        backBtn.setText("<<  Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(titleLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(storeNameLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(storeNameDisplayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prodCatLbl)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(addProdBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(viewDetailsBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(deleteProdBtn))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(backBtn)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(titleLbl)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(storeNameLbl)
                    .addComponent(storeNameDisplayLbl))
                .addGap(34, 34, 34)
                .addComponent(prodCatLbl)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addProdBtn)
                    .addComponent(deleteProdBtn)
                    .addComponent(viewDetailsBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void deleteProdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProdBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = productCatalogTable.getSelectedRow();
        
        if (selectedRow >= 0) {
            int confirmButton = JOptionPane.YES_NO_OPTION;
            
            int confirmDelete = JOptionPane.showConfirmDialog(null, "Would you like to delete selected store admin?", "Warning", confirmButton);
            
            if (confirmDelete == JOptionPane.YES_OPTION) {
                Product product = (Product) productCatalogTable.getValueAt(selectedRow, 1);
                
                store.getProductCatalog().removeProduct(product);
                populateProdTable();
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a row to delete Product!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteProdBtnActionPerformed

    private void addProdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProdBtnActionPerformed
        // TODO add your handling code here:
        AddProductJPanel addProdPanel = new AddProductJPanel(userProcessContainer, store, this);
        userProcessContainer.add("addProdPanel", addProdPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addProdBtnActionPerformed

    private void viewDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = productCatalogTable.getSelectedRow();
        
        if (selectedRow >= 0) {
            Product product = (Product) productCatalogTable.getValueAt(selectedRow, 1);
            
            ViewProductDetailsJPanel viewProdDetailPanel = new ViewProductDetailsJPanel(userProcessContainer, store, product, this);
            userProcessContainer.add("viewProdDetailPanel", viewProdDetailPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a row to view details!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_viewDetailsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProdBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteProdBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel prodCatLbl;
    private javax.swing.JTable productCatalogTable;
    private javax.swing.JLabel storeNameDisplayLbl;
    private javax.swing.JLabel storeNameLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JButton viewDetailsBtn;
    // End of variables declaration//GEN-END:variables
}
