/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.storeadminrole;

import business.enterprise.Enterprise;
import business.organization.Organization;
import business.organization.StoreOrganization;
import business.store.Store;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author JAHNVI
 */
public class StoreAdminWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Organization organization;
    private StoreOrganization storeOrg;
    private Store store;
    private UserAccount userAccount;
    /**
     * Creates new form StoreAdminWorkAreaJPanel
     */
    public StoreAdminWorkAreaJPanel() {
        initComponents();
    }

    public StoreAdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, Organization organization, Store store, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;
        this.storeOrg = (StoreOrganization) organization;
        this.store = store;
        this.userAccount = userAccount;
        displayDetails();
    }

    public void displayDetails() {
        generateReportBtn.setEnabled(false);
        storeNameDisplayLbl.setText(store.getStoreName());
        welcomeMsgLbl.setText(welcomeMsgLbl.getText().replace("<Name>", userAccount.getPerson().getFirstName() + " " + userAccount.getPerson().getLastName()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        welcomeMsgLbl = new javax.swing.JLabel();
        manageProdCatBtn = new javax.swing.JButton();
        generateReportBtn = new javax.swing.JButton();
        storeNameLbl = new javax.swing.JLabel();
        storeNameDisplayLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 102, 102));
        titleLbl.setText("Store Admin - Work Area");

        welcomeMsgLbl.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        welcomeMsgLbl.setForeground(new java.awt.Color(0, 102, 102));
        welcomeMsgLbl.setText("Welcome, <Name>!");

        manageProdCatBtn.setBackground(new java.awt.Color(153, 153, 153));
        manageProdCatBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        manageProdCatBtn.setForeground(new java.awt.Color(0, 102, 102));
        manageProdCatBtn.setText("Manage Product Catalog");
        manageProdCatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProdCatBtnActionPerformed(evt);
            }
        });

        generateReportBtn.setBackground(new java.awt.Color(153, 153, 153));
        generateReportBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        generateReportBtn.setForeground(new java.awt.Color(0, 102, 102));
        generateReportBtn.setText("Generate Reports");

        storeNameLbl.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        storeNameLbl.setForeground(new java.awt.Color(0, 102, 102));
        storeNameLbl.setText("Store Name:");

        storeNameDisplayLbl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        storeNameDisplayLbl.setForeground(new java.awt.Color(0, 102, 102));
        storeNameDisplayLbl.setText("<Store Name>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(welcomeMsgLbl)
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(generateReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageProdCatBtn))
                        .addGap(195, 195, 195))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(titleLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(storeNameLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(storeNameDisplayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(titleLbl)
                .addGap(18, 18, 18)
                .addComponent(welcomeMsgLbl)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(storeNameLbl)
                    .addComponent(storeNameDisplayLbl))
                .addGap(48, 48, 48)
                .addComponent(manageProdCatBtn)
                .addGap(95, 95, 95)
                .addComponent(generateReportBtn)
                .addContainerGap(222, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageProdCatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProdCatBtnActionPerformed
        // TODO add your handling code here:
        ManageProductCatalogJPanel manageProdCatPanel = new ManageProductCatalogJPanel(userProcessContainer, store);
        userProcessContainer.add("manageProdCatPanel", manageProdCatPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageProdCatBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generateReportBtn;
    private javax.swing.JButton manageProdCatBtn;
    private javax.swing.JLabel storeNameDisplayLbl;
    private javax.swing.JLabel storeNameLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel welcomeMsgLbl;
    // End of variables declaration//GEN-END:variables
}
