/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.userrole;

import business.enterprise.Enterprise;
import business.organization.Organization;
import business.person.FamilyMember;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author JAHNVI
 */
public class GenerateUserReportsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Organization organization;
    private UserAccount userAccount;
    
    /**
     * Creates new form GenerateReportsJPanel
     */
    public GenerateUserReportsJPanel() {
        initComponents();
    }

    public GenerateUserReportsJPanel(JPanel userProcessContainer, Enterprise enterprise, Organization organization, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userAccount = userAccount;
        displayDetails();
    }
    
    public void displayDetails() {
        welcomeNameLbl.setText(welcomeNameLbl.getText().replace("<Name>", userAccount.getPerson().getFirstName() + " " + userAccount.getPerson().getLastName()));
        FamilyMember member = (FamilyMember) userAccount.getPerson();
        
        if (member.getVitalSignHistory().getVitalSignHistory().isEmpty()) {
            viewVitalSignTrendsBtn.setEnabled(false);
        }
        else {
            viewVitalSignTrendsBtn.setEnabled(true);
        }
        
        if (member.getFoodConsumptionHistory().getFoodConsumptionDetailHistory().isEmpty()) {
            viewNutrientsTrends.setEnabled(false);
        }
        else {
            viewNutrientsTrends.setEnabled(true);
        }
        
        if (userAccount.getWorkQueue().getWorkRequestList().isEmpty()) {
            errorLbl.setText("No Health Check Reuqest Has Been Made!");
            errorLbl.setVisible(true);
            viewHealthyDaysBtn.setEnabled(false);
            viewUnhealthyDaysBtn.setEnabled(false);
        }
        else {
            errorLbl.setVisible(false);
            viewHealthyDaysBtn.setEnabled(true);
            viewUnhealthyDaysBtn.setEnabled(true);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        welcomeNameLbl = new javax.swing.JLabel();
        viewUnhealthyDaysBtn = new javax.swing.JButton();
        viewHealthyDaysBtn = new javax.swing.JButton();
        viewVitalSignTrendsBtn = new javax.swing.JButton();
        viewNutrientsTrends = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        errorLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 102, 102));
        titleLbl.setText("User - Generate Reports");

        welcomeLbl.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        welcomeLbl.setForeground(new java.awt.Color(0, 102, 102));
        welcomeLbl.setText("Welcome,");

        welcomeNameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        welcomeNameLbl.setForeground(new java.awt.Color(0, 102, 102));
        welcomeNameLbl.setText("<Name>!");

        viewUnhealthyDaysBtn.setBackground(new java.awt.Color(153, 153, 153));
        viewUnhealthyDaysBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewUnhealthyDaysBtn.setForeground(new java.awt.Color(0, 102, 102));
        viewUnhealthyDaysBtn.setText("View Unhealthy Days");
        viewUnhealthyDaysBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUnhealthyDaysBtnActionPerformed(evt);
            }
        });

        viewHealthyDaysBtn.setBackground(new java.awt.Color(153, 153, 153));
        viewHealthyDaysBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewHealthyDaysBtn.setForeground(new java.awt.Color(0, 102, 102));
        viewHealthyDaysBtn.setText("View Healthy Days");
        viewHealthyDaysBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewHealthyDaysBtnActionPerformed(evt);
            }
        });

        viewVitalSignTrendsBtn.setBackground(new java.awt.Color(153, 153, 153));
        viewVitalSignTrendsBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewVitalSignTrendsBtn.setForeground(new java.awt.Color(0, 102, 102));
        viewVitalSignTrendsBtn.setText("View Vital Sign Trends");
        viewVitalSignTrendsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVitalSignTrendsBtnActionPerformed(evt);
            }
        });

        viewNutrientsTrends.setBackground(new java.awt.Color(153, 153, 153));
        viewNutrientsTrends.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewNutrientsTrends.setForeground(new java.awt.Color(0, 102, 102));
        viewNutrientsTrends.setText("View Nutrient Trends");
        viewNutrientsTrends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewNutrientsTrendsActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(153, 153, 153));
        backBtn.setForeground(new java.awt.Color(0, 102, 102));
        backBtn.setText("<<  Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        errorLbl.setForeground(new java.awt.Color(255, 102, 102));
        errorLbl.setText("<Error Message>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titleLbl)
                        .addGap(205, 205, 205))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(welcomeLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(welcomeNameLbl)
                        .addGap(129, 129, 129))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewNutrientsTrends)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(viewUnhealthyDaysBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewHealthyDaysBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewVitalSignTrendsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(errorLbl)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(titleLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcomeLbl)
                    .addComponent(welcomeNameLbl))
                .addGap(71, 71, 71)
                .addComponent(viewHealthyDaysBtn)
                .addGap(42, 42, 42)
                .addComponent(viewUnhealthyDaysBtn)
                .addGap(43, 43, 43)
                .addComponent(viewVitalSignTrendsBtn)
                .addGap(45, 45, 45)
                .addComponent(viewNutrientsTrends)
                .addGap(39, 39, 39)
                .addComponent(errorLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewHealthyDaysBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewHealthyDaysBtnActionPerformed
        // TODO add your handling code here:
        ViewHealthyDaysJPanel viewHealthyDaysPanel = new ViewHealthyDaysJPanel(userProcessContainer, organization , userAccount);
        userProcessContainer.add("viewHealthyDaysPanel", viewHealthyDaysPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewHealthyDaysBtnActionPerformed

    private void viewUnhealthyDaysBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUnhealthyDaysBtnActionPerformed
        // TODO add your handling code here:
        ViewUnhealthyDaysJPanel viewUnhealthyDaysPanel = new ViewUnhealthyDaysJPanel(userProcessContainer, organization , userAccount);
        userProcessContainer.add("viewUnhealthyDaysPanel", viewUnhealthyDaysPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewUnhealthyDaysBtnActionPerformed

    private void viewVitalSignTrendsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVitalSignTrendsBtnActionPerformed
        // TODO add your handling code here:
        ViewVitalSignTrendsJPanel viewVitalTrendsPanel = new ViewVitalSignTrendsJPanel(userProcessContainer, organization , userAccount);
        userProcessContainer.add("viewVitalSignTrendsPanel", viewVitalTrendsPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewVitalSignTrendsBtnActionPerformed

    private void viewNutrientsTrendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewNutrientsTrendsActionPerformed
        // TODO add your handling code here:
        ViewNutrientTrendsJPanel viewNutrientTrendsPanel = new ViewNutrientTrendsJPanel(userProcessContainer, organization, userAccount);
        userProcessContainer.add("viewVitalSignTrendsPanel", viewNutrientTrendsPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewNutrientsTrendsActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel errorLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JButton viewHealthyDaysBtn;
    private javax.swing.JButton viewNutrientsTrends;
    private javax.swing.JButton viewUnhealthyDaysBtn;
    private javax.swing.JButton viewVitalSignTrendsBtn;
    private javax.swing.JLabel welcomeLbl;
    private javax.swing.JLabel welcomeNameLbl;
    // End of variables declaration//GEN-END:variables
}
