/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.userrole;

import business.HelperMethods;
import business.data.FoodConsumptionDetail;
import business.person.FamilyMember;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JAHNVI
 */
public class LookUpFoodConsumptionHistoryJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private FamilyMember member;
    
    /**
     * Creates new form LookUpFoodConsumptionHistoryJPanel
     */
    public LookUpFoodConsumptionHistoryJPanel() {
        initComponents();
    }

    public LookUpFoodConsumptionHistoryJPanel(JPanel userProcessContainer, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.member = (FamilyMember) userAccount.getPerson();
        welcomeNameLbl.setText(welcomeNameLbl.getText().replace("<Name>", userAccount.getPerson().getFirstName() + " " + userAccount.getPerson().getLastName()));
        bindDateCombo();
    }
    
    public void populateFoodConsumptionTable(String date) {
        DefaultTableModel dtm = (DefaultTableModel) foodConsumptionDetailsTable.getModel();
        dtm.setRowCount(0);
        
        for (FoodConsumptionDetail fcd : member.getFoodConsumptionHistory().getFoodConsumptionForDate(date)) {
            Object row[] = new Object[16];
            row[0] = fcd;
            row[1] = fcd.getEnergy();
            row[2] = fcd.getProtien();
            row[3] = fcd.getCarbohydrates();
            row[4] = fcd.getFat();
            row[5] = fcd.getFibers();
            row[6] = fcd.getSugar();
            row[7] = fcd.getSalt();
            row[8] = fcd.getIodine();
            row[9] = fcd.getVitaminA();
            row[10] = fcd.getVitaminB12();
            row[11] = fcd.getVitaminC();
            row[12] = fcd.getVitaminD();
            row[13] = fcd.getVitaminE();
            row[14] = fcd.getVitaminK();
            row[15] = fcd.getSensorName();
            
            dtm.addRow(row);
        }
    }
    
    public void bindDateCombo() {
        dateCombo.removeAllItems();
        
        ArrayList<String> timeStamps = HelperMethods.getListOfTimeStamp(member.getVitalSignHistory());
        ArrayList<String> dates = new ArrayList<>();
        for (String stamp : timeStamps) {
            String date = HelperMethods.getDateFromStamp(stamp);
            
            if (!dates.contains(date)) {
                dates.add(date);
            }
        }
        
        for (String date : dates) {
            dateCombo.addItem(date);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        dateCombo = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        foodConsumptionDetailsTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        welcomeNameLbl = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 102, 102));
        titleLbl.setText("User - Look Up Vital Sign History");

        dateLbl.setForeground(new java.awt.Color(0, 102, 102));
        dateLbl.setText("Date:");

        dateCombo.setForeground(new java.awt.Color(0, 102, 102));
        dateCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dateCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateComboActionPerformed(evt);
            }
        });

        jScrollPane2.setForeground(new java.awt.Color(0, 102, 102));

        foodConsumptionDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Time", "Energy", "Protein", "Carbo.", "Fat", "Fibers", "Sugar", "Salt", "Iodine", "Vit A", "Vit B12", "Vit C", "Vit D", "Vit E", "Vit K", "Sensor Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(foodConsumptionDetailsTable);
        if (foodConsumptionDetailsTable.getColumnModel().getColumnCount() > 0) {
            foodConsumptionDetailsTable.getColumnModel().getColumn(0).setResizable(false);
            foodConsumptionDetailsTable.getColumnModel().getColumn(1).setResizable(false);
            foodConsumptionDetailsTable.getColumnModel().getColumn(2).setResizable(false);
            foodConsumptionDetailsTable.getColumnModel().getColumn(3).setResizable(false);
            foodConsumptionDetailsTable.getColumnModel().getColumn(4).setResizable(false);
            foodConsumptionDetailsTable.getColumnModel().getColumn(5).setResizable(false);
            foodConsumptionDetailsTable.getColumnModel().getColumn(6).setResizable(false);
            foodConsumptionDetailsTable.getColumnModel().getColumn(7).setResizable(false);
            foodConsumptionDetailsTable.getColumnModel().getColumn(8).setResizable(false);
            foodConsumptionDetailsTable.getColumnModel().getColumn(9).setResizable(false);
            foodConsumptionDetailsTable.getColumnModel().getColumn(10).setResizable(false);
            foodConsumptionDetailsTable.getColumnModel().getColumn(11).setResizable(false);
            foodConsumptionDetailsTable.getColumnModel().getColumn(12).setResizable(false);
            foodConsumptionDetailsTable.getColumnModel().getColumn(13).setResizable(false);
            foodConsumptionDetailsTable.getColumnModel().getColumn(14).setResizable(false);
            foodConsumptionDetailsTable.getColumnModel().getColumn(15).setResizable(false);
        }

        backBtn.setBackground(new java.awt.Color(153, 153, 153));
        backBtn.setForeground(new java.awt.Color(0, 102, 102));
        backBtn.setText("<<  Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        welcomeNameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        welcomeNameLbl.setForeground(new java.awt.Color(0, 102, 102));
        welcomeNameLbl.setText("<Name>!");

        welcomeLbl.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        welcomeLbl.setForeground(new java.awt.Color(0, 102, 102));
        welcomeLbl.setText("Welcome,");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(backBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titleLbl)
                        .addGap(203, 203, 203))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(welcomeLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(welcomeNameLbl)
                        .addGap(103, 103, 103))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(241, 241, 241)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(titleLbl)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcomeLbl)
                    .addComponent(welcomeNameLbl))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLbl)
                    .addComponent(dateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(backBtn)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dateComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateComboActionPerformed
        // TODO add your handling code here:
        String date = (String) dateCombo.getSelectedItem();

        if (date != null) {
            populateFoodConsumptionTable(date);
        }
    }//GEN-LAST:event_dateComboActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
       userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox dateCombo;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JTable foodConsumptionDetailsTable;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel welcomeLbl;
    private javax.swing.JLabel welcomeNameLbl;
    // End of variables declaration//GEN-END:variables
}
