/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.userrole;

import business.Constants;
import business.HelperMethods;
import business.enterprise.Enterprise;
import business.organization.HealthCareOrganization;
import business.organization.Organization;
import business.person.FamilyMember;
import business.useraccount.UserAccount;
import business.workqueue.HealthCheckRequest;
import business.workqueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author JAHNVI
 */
public class RequestNewHealthCheckJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Organization organization;
    private UserAccount userAccount;
    private FamilyMember member;
    private RequestHealthCheckJPanel requestHealthCheckPanel;
    
    /**
     * Creates new form RequestNewHealthCheckJPanel
     */
    public RequestNewHealthCheckJPanel() {
        initComponents();
    }

    public RequestNewHealthCheckJPanel(JPanel userProcessContainer, Enterprise enterprise, Organization organization, UserAccount userAccount, RequestHealthCheckJPanel requestHealthCheckPanel) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userAccount = userAccount;
        member = (FamilyMember) this.userAccount.getPerson();
        this.requestHealthCheckPanel = requestHealthCheckPanel;
        displayDetails();
        
                
        if (dateCombo.getItemCount() <= 0) {
            JOptionPane.showMessageDialog(null, "No new health check can be requested!", "Warning", JOptionPane.WARNING_MESSAGE);
            requestBtn.setEnabled(false);
        }
    }
    
    public void displayDetails() {
        welcomeNameLbl.setText(welcomeNameLbl.getText().replace("<Name>", member.getFirstName() + " " + member.getLastName()));
        bindDateCombo();
    }
    
    public void bindDateCombo() {
        dateCombo.removeAllItems();
        
        ArrayList<String> timeStamps = HelperMethods.getListOfTimeStamp(member.getVitalSignHistory());
        ArrayList<String> dates = new ArrayList<>();
        for (String stamp : timeStamps) {
            String date = HelperMethods.getDateFromStamp(stamp) + " 00:00:00";
            
            ArrayList<String> status = new ArrayList<>();
            status.add(Constants.REQUEST_PENDING);
            
            ArrayList<WorkRequest> pendingRequestOnDate = userAccount.getWorkQueue().searchRequestByDate(HelperMethods.getDateForString(date, true), status);
            
            if (!dates.contains(date) && pendingRequestOnDate.isEmpty()) {
                dates.add(HelperMethods.getDateFromStamp(date));
            }
        }
        
        for (String date : dates) {
            dateCombo.addItem(date);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titelLbl = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        welcomeNameLbl = new javax.swing.JLabel();
        selectDateLbl = new javax.swing.JLabel();
        dateCombo = new javax.swing.JComboBox();
        msgLbl = new javax.swing.JLabel();
        msgTxt = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        requestBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        titelLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titelLbl.setForeground(new java.awt.Color(0, 102, 102));
        titelLbl.setText("User - Request a New Health Check");

        welcomeLbl.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        welcomeLbl.setForeground(new java.awt.Color(0, 102, 102));
        welcomeLbl.setText("Welcome,");

        welcomeNameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        welcomeNameLbl.setForeground(new java.awt.Color(0, 102, 102));
        welcomeNameLbl.setText("<Name>!");

        selectDateLbl.setForeground(new java.awt.Color(0, 102, 102));
        selectDateLbl.setText("Select Date:");

        dateCombo.setForeground(new java.awt.Color(0, 102, 102));
        dateCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        msgLbl.setForeground(new java.awt.Color(0, 102, 102));
        msgLbl.setText("Message:");

        msgTxt.setForeground(new java.awt.Color(0, 102, 102));

        backBtn.setBackground(new java.awt.Color(153, 153, 153));
        backBtn.setForeground(new java.awt.Color(0, 102, 102));
        backBtn.setText("<<  Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        requestBtn.setBackground(new java.awt.Color(153, 153, 153));
        requestBtn.setForeground(new java.awt.Color(0, 102, 102));
        requestBtn.setText("Request");
        requestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(backBtn)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titelLbl)
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(msgLbl)
                            .addComponent(selectDateLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(msgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(174, 174, 174))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(requestBtn)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(welcomeLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(welcomeNameLbl)
                        .addGap(108, 108, 108))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(titelLbl)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcomeLbl)
                    .addComponent(welcomeNameLbl))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectDateLbl)
                    .addComponent(dateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(msgLbl)
                    .addComponent(msgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(requestBtn)
                .addGap(157, 157, 157)
                .addComponent(backBtn)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestBtnActionPerformed
        // TODO add your handling code here:
        if (validateInput()) {
            String date = (String) dateCombo.getSelectedItem();
            HealthCheckRequest request = new HealthCheckRequest();
            
            request.setMessage(msgTxt.getText().trim());
            request.setRequestDate(new Date());
            request.setSender(userAccount);
            request.setStatus(Constants.REQUEST_PENDING);
            request.setVitalSignsList(member.getVitalSignHistory().getVitalSignsForDate(date));
            request.setFcdList(member.getFoodConsumptionHistory().getFoodConsumptionForDate(date));
            
            userAccount.getWorkQueue().addWorkRequest(request);
            organization.getWorkQueue().addWorkRequest(request);
                    
            for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (org instanceof HealthCareOrganization) {
                    org.getWorkQueue().addWorkRequest(request);
                    break;
                }
            }
            
            JOptionPane.showMessageDialog(null, "Health Check requested successfully!", "Information", JOptionPane.INFORMATION_MESSAGE);
            bindDateCombo();
            msgTxt.setText("");
            if (dateCombo.getItemCount() <= 0) {
                JOptionPane.showMessageDialog(null, "No new health check can be requested!", "Warning", JOptionPane.WARNING_MESSAGE);
                requestBtn.setEnabled(false);
            }
        }
    }//GEN-LAST:event_requestBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        requestHealthCheckPanel.populateRequestTable((ArrayList) userAccount.getWorkQueue().getWorkRequestList());
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed
    
    public boolean validateInput() {
        if (dateCombo.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(null, "Please select a date to request for health check!", "Error", JOptionPane.ERROR_MESSAGE);
            dateCombo.requestFocus();
            return false;
        }
        else if (msgTxt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a Message!", "Error", JOptionPane.ERROR_MESSAGE);
            msgTxt.requestFocus();
            return false;
        }
        else {
            return true;
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox dateCombo;
    private javax.swing.JLabel msgLbl;
    private javax.swing.JTextField msgTxt;
    private javax.swing.JButton requestBtn;
    private javax.swing.JLabel selectDateLbl;
    private javax.swing.JLabel titelLbl;
    private javax.swing.JLabel welcomeLbl;
    private javax.swing.JLabel welcomeNameLbl;
    // End of variables declaration//GEN-END:variables
}
