/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.userrole;

import business.enterprise.Enterprise;
import business.organization.HouseHoldOrganization;
import business.organization.Organization;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author JAHNVI
 */
public class UserWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Organization organization;
    private UserAccount userAccount;
    private HouseHoldOrganization houseOrg;
    
    /**
     * Creates new form UserWorkAreaJPanel
     */
    public UserWorkAreaJPanel() {
        initComponents();
    }

    public UserWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, Organization organization, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;
        this.houseOrg = (HouseHoldOrganization) organization;
        this.userAccount = userAccount;
        welcomeNameLbl.setText(welcomeNameLbl.getText().replace("<Name>", userAccount.getPerson().getFirstName() + " " + userAccount.getPerson().getLastName()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        welcomeNameLbl = new javax.swing.JLabel();
        manageProfileBtn = new javax.swing.JButton();
        captureVsBtn = new javax.swing.JButton();
        captureFcdBtn = new javax.swing.JButton();
        lookUpVshBtn = new javax.swing.JButton();
        lookUpFchBtn = new javax.swing.JButton();
        requestHealthCheckBtn = new javax.swing.JButton();
        generateReportBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 102, 102));
        titleLbl.setText("User - Work Area");

        welcomeLbl.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        welcomeLbl.setForeground(new java.awt.Color(0, 102, 102));
        welcomeLbl.setText("Welcome,");

        welcomeNameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        welcomeNameLbl.setForeground(new java.awt.Color(0, 102, 102));
        welcomeNameLbl.setText("<Name>!");

        manageProfileBtn.setBackground(new java.awt.Color(153, 153, 153));
        manageProfileBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        manageProfileBtn.setForeground(new java.awt.Color(0, 102, 102));
        manageProfileBtn.setText("Manage Profile");
        manageProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProfileBtnActionPerformed(evt);
            }
        });

        captureVsBtn.setBackground(new java.awt.Color(153, 153, 153));
        captureVsBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        captureVsBtn.setForeground(new java.awt.Color(0, 102, 102));
        captureVsBtn.setText("Capture Vital Signs");
        captureVsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                captureVsBtnActionPerformed(evt);
            }
        });

        captureFcdBtn.setBackground(new java.awt.Color(153, 153, 153));
        captureFcdBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        captureFcdBtn.setForeground(new java.awt.Color(0, 102, 102));
        captureFcdBtn.setText("Capture Food Consumption Details");
        captureFcdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                captureFcdBtnActionPerformed(evt);
            }
        });

        lookUpVshBtn.setBackground(new java.awt.Color(153, 153, 153));
        lookUpVshBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lookUpVshBtn.setForeground(new java.awt.Color(0, 102, 102));
        lookUpVshBtn.setText("Look Up Vital Sign History");
        lookUpVshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookUpVshBtnActionPerformed(evt);
            }
        });

        lookUpFchBtn.setBackground(new java.awt.Color(153, 153, 153));
        lookUpFchBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lookUpFchBtn.setForeground(new java.awt.Color(0, 102, 102));
        lookUpFchBtn.setText("Look Up Food Consumption History");
        lookUpFchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookUpFchBtnActionPerformed(evt);
            }
        });

        requestHealthCheckBtn.setBackground(new java.awt.Color(153, 153, 153));
        requestHealthCheckBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        requestHealthCheckBtn.setForeground(new java.awt.Color(0, 102, 102));
        requestHealthCheckBtn.setText("Request Health Check");
        requestHealthCheckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestHealthCheckBtnActionPerformed(evt);
            }
        });

        generateReportBtn.setBackground(new java.awt.Color(153, 153, 153));
        generateReportBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        generateReportBtn.setForeground(new java.awt.Color(0, 102, 102));
        generateReportBtn.setText("Generate Reports");
        generateReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(welcomeLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeNameLbl)
                .addGap(120, 120, 120))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(titleLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(captureFcdBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(captureVsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageProfileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lookUpVshBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lookUpFchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(requestHealthCheckBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(generateReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(169, 169, 169))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titleLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcomeLbl)
                    .addComponent(welcomeNameLbl))
                .addGap(46, 46, 46)
                .addComponent(manageProfileBtn)
                .addGap(18, 18, 18)
                .addComponent(captureVsBtn)
                .addGap(18, 18, 18)
                .addComponent(captureFcdBtn)
                .addGap(18, 18, 18)
                .addComponent(lookUpVshBtn)
                .addGap(18, 18, 18)
                .addComponent(lookUpFchBtn)
                .addGap(18, 18, 18)
                .addComponent(requestHealthCheckBtn)
                .addGap(18, 18, 18)
                .addComponent(generateReportBtn)
                .addContainerGap(127, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProfileBtnActionPerformed
        // TODO add your handling code here:
        ManageProfileJPanel manageProfilePanel = new ManageProfileJPanel(userProcessContainer, houseOrg, userAccount);
        userProcessContainer.add("manageProfilePanel", manageProfilePanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageProfileBtnActionPerformed

    private void captureVsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_captureVsBtnActionPerformed
        // TODO add your handling code here:
        CaptureVitalSignJPanel captureVsPanel = new CaptureVitalSignJPanel(userProcessContainer, userAccount);
        userProcessContainer.add("captureVsPanel", captureVsPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_captureVsBtnActionPerformed

    private void captureFcdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_captureFcdBtnActionPerformed
        // TODO add your handling code here:
        CaptureFoodConsumptionDetailJPanel captureFcdPanel = new CaptureFoodConsumptionDetailJPanel(userProcessContainer, userAccount);
        userProcessContainer.add("captureFcdPanel", captureFcdPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_captureFcdBtnActionPerformed

    private void lookUpVshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookUpVshBtnActionPerformed
        // TODO add your handling code here:
        LookUpVitalSignHistoryJPanel lookUpVshPanel = new LookUpVitalSignHistoryJPanel(userProcessContainer, userAccount);
        userProcessContainer.add("lookUpVshPanel", lookUpVshPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_lookUpVshBtnActionPerformed

    private void lookUpFchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookUpFchBtnActionPerformed
        // TODO add your handling code here:
        LookUpFoodConsumptionHistoryJPanel lookUpFchPanel = new LookUpFoodConsumptionHistoryJPanel(userProcessContainer, userAccount);
        userProcessContainer.add("lookUpFchPanel", lookUpFchPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_lookUpFchBtnActionPerformed

    private void requestHealthCheckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestHealthCheckBtnActionPerformed
        // TODO add your handling code here:
        RequestHealthCheckJPanel requestHealthCheckPanel = new RequestHealthCheckJPanel(userProcessContainer, enterprise, organization, userAccount);
        userProcessContainer.add("requestHealthCheckPanel", requestHealthCheckPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestHealthCheckBtnActionPerformed

    private void generateReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportBtnActionPerformed
        // TODO add your handling code here:
        GenerateUserReportsJPanel generateUserReportPanel = new GenerateUserReportsJPanel(userProcessContainer, enterprise, organization, userAccount);
        userProcessContainer.add("generateUserReportPanel", generateUserReportPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_generateReportBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton captureFcdBtn;
    private javax.swing.JButton captureVsBtn;
    private javax.swing.JButton generateReportBtn;
    private javax.swing.JButton lookUpFchBtn;
    private javax.swing.JButton lookUpVshBtn;
    private javax.swing.JButton manageProfileBtn;
    private javax.swing.JButton requestHealthCheckBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel welcomeLbl;
    private javax.swing.JLabel welcomeNameLbl;
    // End of variables declaration//GEN-END:variables
}
