/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.userrole;

import business.HelperMethods;
import business.data.FoodConsumptionDetail;
import business.data.VitalSign;
import business.organization.Organization;
import business.person.FamilyMember;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.ItemLabelAnchor;
import org.jfree.chart.labels.ItemLabelPosition;
import org.jfree.chart.labels.StandardCategoryItemLabelGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.ui.TextAnchor;

/**
 *
 * @author JAHNVI
 */
public class ViewNutrientTrendsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private FamilyMember member;
    private ArrayList<FoodConsumptionDetail> nutrientList;
    
    /**
     * Creates new form ViewNutrientTrendsJPanel
     */
    public ViewNutrientTrendsJPanel() {
        initComponents();
    }

    public ViewNutrientTrendsJPanel(JPanel userProcessContainer, Organization organization, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.userAccount = userAccount;
        this.member = (FamilyMember) this.userAccount.getPerson();
        displayDetails();
        this.nutrientList = member.getFoodConsumptionHistory().getFoodConsumptionDetailHistory();
    }
    
    public void displayDetails() {
        welcomeNameLbl.setText(welcomeNameLbl.getText().replace("<Name>", userAccount.getPerson().getFirstName() + " " + userAccount.getPerson().getLastName()));
        bindDateCombo();
    }
    
    public void bindDateCombo() {
        dateCombo.removeAllItems();
        
        ArrayList<String> timeStamps = HelperMethods.getListOfTimeStamp(member.getVitalSignHistory());
        ArrayList<String> dates = new ArrayList<>();
        for (String stamp : timeStamps) {
            String date = HelperMethods.getDateFromStamp(stamp);
            
            if (!dates.contains(date)) {
                dates.add(date);
            }
        }
        
        for (String date : dates) {
            dateCombo.addItem(date);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        welcomeNameLbl = new javax.swing.JLabel();
        selectDateLbl = new javax.swing.JLabel();
        dateCombo = new javax.swing.JComboBox();
        seeTrendCheck = new javax.swing.JCheckBox();
        viewTrendBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 102, 102));
        titleLbl.setText("User - View Nutrient Trends");

        welcomeLbl.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        welcomeLbl.setForeground(new java.awt.Color(0, 102, 102));
        welcomeLbl.setText("Welcome,");

        welcomeNameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        welcomeNameLbl.setForeground(new java.awt.Color(0, 102, 102));
        welcomeNameLbl.setText("<Name>!");

        selectDateLbl.setForeground(new java.awt.Color(0, 102, 102));
        selectDateLbl.setText("Select a day:");

        dateCombo.setForeground(new java.awt.Color(0, 102, 102));
        dateCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dateCombo.setEnabled(false);
        dateCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateComboActionPerformed(evt);
            }
        });

        seeTrendCheck.setForeground(new java.awt.Color(0, 102, 102));
        seeTrendCheck.setText("See trend for a day");
        seeTrendCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeTrendCheckActionPerformed(evt);
            }
        });

        viewTrendBtn.setBackground(new java.awt.Color(153, 153, 153));
        viewTrendBtn.setForeground(new java.awt.Color(0, 102, 102));
        viewTrendBtn.setText("View Trends");
        viewTrendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTrendBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(153, 153, 153));
        backBtn.setForeground(new java.awt.Color(0, 102, 102));
        backBtn.setText("<<  Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selectDateLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(seeTrendCheck)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titleLbl)
                            .addComponent(welcomeLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(welcomeNameLbl)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(viewTrendBtn)
                        .addGap(242, 242, 242))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(titleLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcomeLbl)
                    .addComponent(welcomeNameLbl))
                .addGap(92, 92, 92)
                .addComponent(seeTrendCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectDateLbl)
                    .addComponent(dateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(viewTrendBtn)
                .addGap(178, 178, 178)
                .addComponent(backBtn)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dateComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateComboActionPerformed
        // TODO add your handling code here:
        String date = (String) dateCombo.getSelectedItem();

        if (date != null) {
            nutrientList = member.getFoodConsumptionHistory().getFoodConsumptionForDate(date);
        }
    }//GEN-LAST:event_dateComboActionPerformed

    private void seeTrendCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeTrendCheckActionPerformed
        // TODO add your handling code here:
        if (seeTrendCheck.isSelected()) {
            dateCombo.setEnabled(true);
        }

        if (!seeTrendCheck.isSelected()) {
            dateCombo.setEnabled(false);
        }
    }//GEN-LAST:event_seeTrendCheckActionPerformed

    private void viewTrendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTrendBtnActionPerformed
        // TODO add your handling code here:
        generateTrendsReport(nutrientList);
    }//GEN-LAST:event_viewTrendBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    public void generateTrendsReport(ArrayList<FoodConsumptionDetail> nutrientsList) {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        for (FoodConsumptionDetail fcd : nutrientsList) {
            Double energy = Double.parseDouble(String.valueOf(fcd.getEnergy()));
            Double protien = Double.parseDouble(String.valueOf(fcd.getProtien()));
            Double fat = Double.parseDouble(String.valueOf(fcd.getFat()));
            Double carbo = Double.parseDouble(String.valueOf(fcd.getCarbohydrates()));
            Double fibers = Double.parseDouble(String.valueOf(fcd.getFibers()));
            Double sugar = Double.parseDouble(String.valueOf(fcd.getSugar()));
            Double salt = Double.parseDouble(String.valueOf(fcd.getSalt()));
            Double iodine = Double.parseDouble(String.valueOf(fcd.getIodine()));
            Double vitA = Double.parseDouble(String.valueOf(fcd.getVitaminA()));
            Double vitB12 = Double.parseDouble(String.valueOf(fcd.getVitaminB12()));
            Double vitC = Double.parseDouble(String.valueOf(fcd.getVitaminC()));
            Double vitD = Double.parseDouble(String.valueOf(fcd.getVitaminD()));
            Double vitE = Double.parseDouble(String.valueOf(fcd.getVitaminE()));
            Double vitK = Double.parseDouble(String.valueOf(fcd.getVitaminK()));
            
            dataset.addValue(energy, "Energy", fcd.getTimestamp());
            dataset.addValue(protien, "Protien", fcd.getTimestamp());
            dataset.addValue(fat, "Fat", fcd.getTimestamp());
            dataset.addValue(carbo, "Carbohydrates", fcd.getTimestamp());
            dataset.addValue(fibers, "Fibers", fcd.getTimestamp());
            dataset.addValue(sugar, "Sugar", fcd.getTimestamp());
            dataset.addValue(salt, "Salt", fcd.getTimestamp());
            dataset.addValue(iodine, "Iodine", fcd.getTimestamp());
            dataset.addValue(vitA, "Vitamin A", fcd.getTimestamp());
            dataset.addValue(vitB12, "Vitamin B12", fcd.getTimestamp());
            dataset.addValue(vitC, "Vitamin C", fcd.getTimestamp());
            dataset.addValue(vitD, "VItamin D", fcd.getTimestamp());
            dataset.addValue(vitE, "Vitamin E", fcd.getTimestamp());
            dataset.addValue(vitK, "Vitamin K", fcd.getTimestamp());            
        }
        
        JFreeChart chart = ChartFactory.createLineChart("Vital Sign Trends", "Vital Signs", "Values", dataset);
        
        final CategoryPlot plot = chart.getCategoryPlot();
        
        LineAndShapeRenderer renderer = (LineAndShapeRenderer) plot.getRenderer();
        DecimalFormat decimalFormat = new DecimalFormat("####.##");
        renderer.setShapesVisible(true);
        renderer.setItemLabelGenerator(new StandardCategoryItemLabelGenerator("{2}", decimalFormat));
        plot.setRenderer(renderer);
        renderer.setPositiveItemLabelPosition(new ItemLabelPosition(ItemLabelAnchor.OUTSIDE12, TextAnchor.HALF_ASCENT_CENTER));
        renderer.setItemLabelsVisible(true);
        chart.getCategoryPlot().setRenderer(renderer);
        
        ChartFrame frame = new ChartFrame("Vital Sign Trends", chart);
        frame.setVisible(true);
        frame.setSize(650, 650);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox dateCombo;
    private javax.swing.JCheckBox seeTrendCheck;
    private javax.swing.JLabel selectDateLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JButton viewTrendBtn;
    private javax.swing.JLabel welcomeLbl;
    private javax.swing.JLabel welcomeNameLbl;
    // End of variables declaration//GEN-END:variables
}
