/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.storeorganizationadminrole;

import business.EcoSystem;
import business.enterprise.Enterprise;
import business.organization.Organization;
import business.organization.StoreOrganization;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author JAHNVI
 */
public class StoreOrganizationAdminWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private Enterprise enterprise;
    private Organization organization;
    private UserAccount userAccount;
    
    /**
     * Creates new form StoreOrganizationAdminWorkAreaJPanel
     */
    public StoreOrganizationAdminWorkAreaJPanel() {
        initComponents();
    }

    public StoreOrganizationAdminWorkAreaJPanel(JPanel userProcessContainer, EcoSystem system, Enterprise enterprise, Organization organization, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userAccount = userAccount;
        displayDetails();
    }
    
    public void displayDetails() {
        welcomeMsgLbl.setText(welcomeMsgLbl.getText().replace("<Name>", userAccount.getPerson().getFirstName() + " " + userAccount.getPerson().getLastName()));
        
        StoreOrganization org = (StoreOrganization) organization;
        
        if (org.getStoreDirectory().getStoreList().isEmpty()) {
            manageStoreAdminBtn.setEnabled(false);
            generateReportsBtn.setEnabled(false);
        }
        else {
            manageStoreAdminBtn.setEnabled(true);
            generateReportsBtn.setEnabled(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        welcomeMsgLbl = new javax.swing.JLabel();
        manageStoreBtn = new javax.swing.JButton();
        manageStoreAdminBtn = new javax.swing.JButton();
        generateReportsBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 102, 102));
        titleLbl.setText("Store Organization Admin - Work Area");

        welcomeMsgLbl.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        welcomeMsgLbl.setForeground(new java.awt.Color(0, 102, 102));
        welcomeMsgLbl.setText("Welcome, <Name>!");

        manageStoreBtn.setBackground(new java.awt.Color(153, 153, 153));
        manageStoreBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        manageStoreBtn.setForeground(new java.awt.Color(0, 102, 102));
        manageStoreBtn.setText("Manage Store");
        manageStoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStoreBtnActionPerformed(evt);
            }
        });

        manageStoreAdminBtn.setBackground(new java.awt.Color(153, 153, 153));
        manageStoreAdminBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        manageStoreAdminBtn.setForeground(new java.awt.Color(0, 102, 102));
        manageStoreAdminBtn.setText("Manage Store Admin");
        manageStoreAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStoreAdminBtnActionPerformed(evt);
            }
        });

        generateReportsBtn.setBackground(new java.awt.Color(153, 153, 153));
        generateReportsBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        generateReportsBtn.setForeground(new java.awt.Color(0, 102, 102));
        generateReportsBtn.setText("Generate Reports");
        generateReportsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(titleLbl)
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(manageStoreBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageStoreAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generateReportsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(237, 237, 237))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(welcomeMsgLbl)
                        .addGap(125, 125, 125))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(titleLbl)
                .addGap(40, 40, 40)
                .addComponent(welcomeMsgLbl)
                .addGap(70, 70, 70)
                .addComponent(manageStoreBtn)
                .addGap(41, 41, 41)
                .addComponent(manageStoreAdminBtn)
                .addGap(40, 40, 40)
                .addComponent(generateReportsBtn)
                .addGap(222, 222, 222))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageStoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStoreBtnActionPerformed
        // TODO add your handling code here:
        ManageStoreJPanel manageStorePanel = new ManageStoreJPanel(userProcessContainer, organization, this);
        userProcessContainer.add("manageStorePanel", manageStorePanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageStoreBtnActionPerformed

    private void manageStoreAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStoreAdminBtnActionPerformed
        // TODO add your handling code here:
        ManageStoreAdminJPanel manageStoreAdminPanel = new ManageStoreAdminJPanel(userProcessContainer, system, organization);
        userProcessContainer.add("manageStoreAdminPanel", manageStoreAdminPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageStoreAdminBtnActionPerformed

    private void generateReportsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generateReportsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generateReportsBtn;
    private javax.swing.JButton manageStoreAdminBtn;
    private javax.swing.JButton manageStoreBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel welcomeMsgLbl;
    // End of variables declaration//GEN-END:variables
}
