/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.healthcareorganizationadminrole;

import business.EcoSystem;
import business.enterprise.Enterprise;
import business.organization.Organization;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author JAHNVI
 */
public class HealthCareOrganizationAdminWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private Enterprise enterprise;
    private Organization organization;
    private UserAccount userAccount;
    /**
     * Creates new form HealthCareOrganizationAdminWorkAreaJPanel
     */
    public HealthCareOrganizationAdminWorkAreaJPanel() {
        initComponents();
    }

    public HealthCareOrganizationAdminWorkAreaJPanel(JPanel userProcessContainer, EcoSystem system, Enterprise enterprise, Organization organization, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userAccount = userAccount;
        
        welcomeMsgLbl.setText(welcomeMsgLbl.getText().replace("<Name>", userAccount.getPerson().getFirstName() + " " + userAccount.getPerson().getLastName()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titelLbl = new javax.swing.JLabel();
        welcomeMsgLbl = new javax.swing.JLabel();
        manageHealthAnalystBtn = new javax.swing.JButton();
        generateReportsBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(740, 670));

        titelLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titelLbl.setForeground(new java.awt.Color(0, 102, 102));
        titelLbl.setText("Health Care Organization Admin - Work Area");

        welcomeMsgLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        welcomeMsgLbl.setForeground(new java.awt.Color(0, 102, 102));
        welcomeMsgLbl.setText("Welcome, <Name>!");

        manageHealthAnalystBtn.setBackground(new java.awt.Color(153, 153, 153));
        manageHealthAnalystBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        manageHealthAnalystBtn.setForeground(new java.awt.Color(0, 102, 102));
        manageHealthAnalystBtn.setText("Manage Health Analyst");
        manageHealthAnalystBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageHealthAnalystBtnActionPerformed(evt);
            }
        });

        generateReportsBtn.setBackground(new java.awt.Color(153, 153, 153));
        generateReportsBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        generateReportsBtn.setForeground(new java.awt.Color(0, 102, 102));
        generateReportsBtn.setText("Generate Reports");
        generateReportsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(titelLbl)
                .addContainerGap(196, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manageHealthAnalystBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(generateReportsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(281, 281, 281))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(welcomeMsgLbl)
                        .addGap(152, 152, 152))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titelLbl)
                .addGap(71, 71, 71)
                .addComponent(welcomeMsgLbl)
                .addGap(139, 139, 139)
                .addComponent(manageHealthAnalystBtn)
                .addGap(42, 42, 42)
                .addComponent(generateReportsBtn)
                .addContainerGap(306, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageHealthAnalystBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageHealthAnalystBtnActionPerformed
        // TODO add your handling code here:
        ManageHealthAnalystJPanel manageAnalystPanel = new ManageHealthAnalystJPanel(userProcessContainer, system, organization);
        userProcessContainer.add("manageAnalystPanel", manageAnalystPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageHealthAnalystBtnActionPerformed

    private void generateReportsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportsBtnActionPerformed
        // TODO add your handling code here:
        GenerateHealthOrgReportsJPanel generateHealthOrgReportsPanel = new GenerateHealthOrgReportsJPanel(userProcessContainer, organization, userAccount);
        userProcessContainer.add("generateHealthOrgReportPanel", generateHealthOrgReportsPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_generateReportsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generateReportsBtn;
    private javax.swing.JButton manageHealthAnalystBtn;
    private javax.swing.JLabel titelLbl;
    private javax.swing.JLabel welcomeMsgLbl;
    // End of variables declaration//GEN-END:variables
}
